Infomaniak/android-kMail

app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Display "No subject" when needed in Threads list & Messages list

---

app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Listen to network status

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt

Some fixes

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt

#05: Use `enumValueOfOrNull<T>`

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values-v27/themes.xml
app/src/main/res/values/themes.xml

Fix login Activity crash when deleting `windowActionBar`

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/res/layout/fragment_thread.xml
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values/themes.xml

Add `collapsingToolbarLayout` to Thread fragment

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/res/layout/fragment_thread_list.xml

Add SwipeRefreshLayout in Threads list

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/res/layout/item_thread.xml
app/src/main/res/values/styles.xml

Add ripple effect on Threads list cardview

---

app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

Fix RealmList serialization issues

---

app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt

Fix Realm cleaning

---

app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

Drafts in Realm

---

app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
app/src/main/java/com/infomaniak/mail/data/api/RealmListSerializer.kt
app/src/main/java/com/infomaniak/mail/data/cache/AppSettingsController.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
app/src/main/java/com/infomaniak/mail/data/models/signature/SignatureEmail.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/data/models/user/UserInfos.kt
app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Update Realm package (from `io.realm` to `io.realm.kotlin`)

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt

The fab will now expand on scroll up and collapse on scroll down
Depends on #130

NewMessage fab shrink on scroll down and expand on scroll up

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
build.gradle
gradle.properties

Rework Realm

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAccountAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAddressAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchUserViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/drawable/ic_plus_rounded.xml
app/src/main/res/layout/fragment_switch_user.xml
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/layout/item_setting_account.xml
app/src/main/res/layout/item_setting_address.xml
app/src/main/res/menu/account_menu.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Account menu

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/res/layout/item_message.xml

Add listener on header to expand it on click

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/layout/fragment_cancel_delay_setting.xml
app/src/main/res/layout/fragment_external_content_setting.xml
app/src/main/res/layout/fragment_message_display_mode_setting.xml
app/src/main/res/layout/fragment_message_list_density_setting.xml
app/src/main/res/layout/fragment_switch_user.xml
app/src/main/res/layout/fragment_theme_setting.xml
app/src/main/res/layout/item_search_view.xml
app/src/main/res/layout/item_setting_account.xml
app/src/main/res/layout/item_setting_address.xml
app/src/main/res/xml/data_extraction_rules.xml

Gradle and core

---

app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Mark as seen

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt

Fix Messages' bodies that are re-downloaded each time a Thread is opened

---

app/build.gradle

Bump to Android 32

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/ContactsController.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Add Contact & AddressBook

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Remove use of GlobalScope

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt

Better naming

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Attachments

---

app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/models/MessagePriority.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt

Random fixes related to PR reviews

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt

Fix never ending refresh of empty Folder

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FoldersAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/res/layout/item_folder_menu_drawer.xml

Display Folders' children in MenuDrawer

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/layout/fragment_menu_drawer.xml
app/src/main/res/layout/fragment_thread.xml
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/item_switch_user_account.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
build.gradle

Fix some TODOs

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
app/src/main/java/com/infomaniak/mail/data/cache/ContactsController.kt
app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt

Add Address Books API call

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Replace Flow in fragments with Livedata

---

app/src/main/java/com/infomaniak/mail/data/MailData.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FoldersAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
app/src/main/res/layout/fragment_menu_drawer.xml

`CreateNewFolder` button in MenuDrawer (UI only)

---

app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserAccountsAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newmessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
app/src/main/java/com/infomaniak/mail/utils/KMailHttpClient.kt

Add empty line before `return` statements

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt

Fix Folder's unread count in Threads list

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt

Remove `observeOnce` + Use `AccountUtils.getAllUsersSync()` instead of `getAllusers`

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Display last Message preview in Threads list

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/res/layout/fragment_thread.xml

Uniformize adapters

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt

Fix crash when opening Mailbox

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt

Listen Realm in SwitchUser menu

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt

Get Realm flows synchronously when it's useless to get them asynchronously

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Duplicate.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt

Closes #215
Closes #216
Depends on #204

Handle duplicated Messages + Fix MarkAsSeen

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/data/models/Correspondent.kt
app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt

Move a few needed functions in `Correspondent`

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/res/layout/item_message.xml

Add `Bcc` field to the details of sent/received mails

---

app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt

Put back ShowLoading timer in Threads list

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

* New mail email popup now is also dismissed when clicking on its opening button as well
* Use SingleLiveEvent
* Simplified concatenation of recipient names

Small feedbacks fixes

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt

Fix empty Realm at login

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Replace `LiveData.value` with `LiveData.postValue`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt

Refactor ViewModel LiveData

---

app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt

Remove Realm `findLatest`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt

Rename controllers functions

---

app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
app/src/main/java/com/infomaniak/mail/data/models/user/UserResult.kt

Add `@Transient` & `@Ignore` in Models when needed

---

app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt

Clean Quotas code

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt

Move `startUpdatedAtJob` to ViewModel

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Fix `markAsSeen` so it updates the Folder's `unreadCount`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Swipe Thread as unseen

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt

Create a Realm DiffUtil to notify an adapter for all Realm changes automatically

Realm DiffUtil

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt

Code cleaning

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt

Simplify DB upserts

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Quotas are missing, they are in the next PR: #257
Depends on #247

Embedded objects

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt

Embedded Quotas

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt

Easier way of accessing attributes in custom views (factorized)

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Fix Login `accentColor`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/res/navigation/main_navigation.xml

Directly go to NewMessage when opening a Thread that is just 1 Draft

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Add Signature in Draft

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/SaveDraftResult.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/res/navigation/main_navigation.xml

Refactor Drafts to use `LocalUuid` & `RemoteUuid`

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt

Rename all `listenTo` into `observe`

---

.idea/navEditor.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/res/values/themes.xml
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Needs https://github.com/Infomaniak/android-core/pull/14 to be reviewed

Add Bugs tracker

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/navigation/main_navigation.xml

Implement `Reply` & `Reply all`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Get last Message to execute action

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt

Blocked by https://github.com/Infomaniak/android-core/pull/15

Implement Matomo tracker

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Some comments from #314 were forgotten, they're implemented here.
Depends on #316

Handle previous Github comments

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/navigation/main_navigation.xml

- Save Draft when leaving NewMessage screen
- Fetch Draft when opening NewMessage screen
- Update Message when Draft is fetched
Depends on #321

Update fetch & save/send Draft policies

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt

Revamp LiveData

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt

Handle `Reply`, `Reply All` & `Forward` subject prefixes

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Manage all drafts actions with a worker

Drafts actions worker

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add prefix (Draft) in thread list

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Download Attachments work

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Keep the `Thread` object in `ThreadViewModel`

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt

Depends on https://github.com/Infomaniak/android-core/pull/20

Fix Folder's start margin

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/item_attachment.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on https://github.com/Infomaniak/android-core/pull/21

UI for adding Attachments when composing new Message

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/res/layout/view_empty_state.xml

* TextViews didn't need to be set to gone in XML because the custom view class handles its visibility anyway
* The delete and read/unread swipe settings are implemented and therefore should not display the message "not yet implemented"

Fix small details

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Put back the `Unread` filter

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Add `getCurrentMailbox` & `getCurrentMailboxUuid` helpers

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Optimize `toggleSeenStatus` realm usage

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt

Rename `api` variables into `remote`

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/res/layout/view_avatar.xml

* Fix a crash when opening menu drawer for api < 26
* Fix invisible avatars throughout the app for lower api versions
* Update minSdk to 25 because of invisible swipe action preview in settings

Multiple fixes for lower api versions

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsDeltaResult.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Create Threads with multiple Messages

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/BaseCoroutineWorker.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

A base of network CoroutineWorker
Depends on #368

Base network coroutine worker

---

app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
app/src/main/res/layout/item_folder_menu_drawer.xml
app/src/main/res/layout/item_menu_drawer.xml
app/src/main/res/layout/item_switch_user_mailbox_menu_drawer.xml
app/src/main/res/values/attrs.xml

Refacto `unreadCount` display

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt

Currently we have two permissions in the app but they are not processed. And so we have just one of the two permissions that are running.

Request multiple permissions needed from MainActivity

---

app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Navigate to `ThreadListFragment` when a new message notification has been clicked

Deeplink for new message Notification click

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/BaseCoroutineWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
app/src/main/res/navigation/main_navigation.xml

Handle notification click open thread

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserMailboxesAdapter.kt

Rework Folder `unreadCount`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt

Folders rules

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/res/layout/bottom_sheet_actions_menu.xml

Refacto `read`/`unread` actions on Thread

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Refacto `delete` action on Thread & Draft in a Thread

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt

Sentry: https://sentry.infomaniak.com/organizations/infomaniak/issues/63999/?project=45&query=&statsPeriod=14d

Fix invalid MergedContact

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt

**Features**
- Handle `ACTION_SEND` (text or attachment) and `ACTION_SEND_MULTIPLE` with attachments
- Handle `mailto` from `ACTION_VIEW` or `ACTION_SENDTO`
**Fix**
- intent has null extras with navArgs when navigate with deeplink from `ACTION_SENDTO` intent

Handle SendTo

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/ManageMailAddressViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SimpleMailboxAdapter.kt
app/src/main/res/layout/fragment_manage_mail_address.xml
app/src/main/res/layout/item_mailbox_my_account.xml

Now lists mailboxes in profile

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt

Enable favorite swipe action, and remove the notYetImplementedSnackbar on the 'none' swipe action

Favorite swipe action

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Remove API calls from DraftController

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/res/navigation/main_navigation.xml

Add swipe action to open the thread action menu

Add QuickMenu swipe action

---

app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Group messages notifications by mailbox

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Remove API calls from ThreadController

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Fix Sentry https://sentry.infomaniak.com/share/issue/0fd7f2da1bcd48c78ed6c27a00a19692/

fix: invalid folder from CompletedWorkInfosLiveData

---

app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Fix sentry https://sentry.infomaniak.com/share/issue/46cd043bcd784e1ca1901b2187de297d/

fix: invalidated object

---

app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Sentry https://sentry.infomaniak.com/share/issue/6fd780bc9ef547eab28811d584b95d5e/

fix: add more sentry log when an exception has been triggered

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Get 500 last Messages instead of 3 months of data when opening a Folder for the 1st time

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Refresh all concerned Folders when executing an action

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Add read and archive Swipe action
Depends on #465

Read and Archive swipe action

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Don't display empty view when 1st opening of a Folder

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Refactor actions

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

When we display a message, we also download its body, but for the display of the body we parse it in html, while filtering the images

feat: download notifications messages body

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/SendDraftResult.kt
app/src/main/java/com/infomaniak/mail/data/models/message/DeleteMessageResult.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Display new Message in Thread after sending it

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Replace `Transformations.switchMap` with kotlin extension 
Depends on #498

replace switchMap with kotlin extension switchMap

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Display received mails in dark mode

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Remove useless controllers calls to get thread and message in every actions.
Depends on #481

Remove useless controller calls

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

Merge "Message & Thread as Favorites" functions into one

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Add Read/Unread action on Message

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
app/src/main/res/layout/item_switch_user_mailbox_menu_drawer.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml

Display `99+` unread count when there is too much messages.

...but a b*tch ain't one

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Manage actions cancelling

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Correctly display Messages when moving a Message

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
app/src/main/res/navigation/main_navigation.xml

Use Realm `queries` to get Messages for Actions functions

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Remove useless default `null` value for some Realm objects

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Invert some `if` conditions

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Correctly refresh UI Draft when coming back to app

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Fix sentry https://sentry.infomaniak.com/share/issue/cbce3ed04f7949d6a84dbbb196ca84ef/

fix: lateinit property snapshot has not been initialized

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

- [fix: message notification show css](https://github.com/Infomaniak/android-mail/pull/531/commits/6a853de67e6039e54c3bbad72c29da35d1415e00)
- [fix: body missing in message notification](https://github.com/Infomaniak/android-mail/pull/531/commits/c13e21bee1d0045d7a245289e027cebd676acb75)

Fix: sync messages body

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Enable marking user's own messages as spam

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt

Fix Sentry https://sentry.infomaniak.com/share/issue/6bc5fa1289514dbebcec104b1999caff/

fix: out of memory when delete messages delta

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

Update MenuDrawer badge for DRAFT, SENT & TRASH

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/res/layout/fragment_settings.xml

- Disable access to Search feature
- Hide "Display external content" feature
- Hide "App lock" feature
- Hide "Emails addresses" menu
- Hide "Send" menu
- Remove header of empty Settings sections

Disable some features

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/res/drawable/ic_open_external.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/view_item_setting.xml
app/src/main/res/values/attrs.xml

Depends on #546 
Depends on https://github.com/Infomaniak/android-core/pull/30

Add Notifications setting

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt

Fix sentry https://sentry.infomaniak.com/share/issue/4ea3c3354d7241c4a96d5dae2ea8b050/

fix: Can't toast on a thread that has not called Looper.prepare()

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/layout/item_mailbox_my_account.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/item_thread_date_separator.xml
app/src/main/res/layout/view_item_setting.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

Depends on https://github.com/Infomaniak/android-core/pull/31

New thread densities

---

app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Fix sentry https://sentry.infomaniak.com/share/issue/6fd780bc9ef547eab28811d584b95d5e/

fix: Handle all api errors exception in SyncMessageWorker

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/res/layout/fragment_menu_drawer.xml
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/fragment_thread.xml
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/item_search_view.xml
app/src/main/res/layout/view_main_actions.xml
app/src/main/res/layout/view_menu_drawer_dropdown.xml
app/src/main/res/layout/view_recipient_field.xml
app/src/main/res/values/styles.xml

https://m3.material.io/components/icon-buttons/specs#7b6741d2-09f0-488e-abeb-fc6dd27b447d

Comply with material guidelines for icon buttons target size and update to follow mockups

---

app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/layout/fragment_menu_drawer.xml
app/src/main/res/layout/view_menu_drawer_dropdown.xml
app/src/main/res/layout/view_recipient_field.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Color updates in dark mode:
* Primary text
* Fragment's headers
* Icons (additional icon style)

First update for the new dark theme

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

refactor(Move): Factorize Move and Archive functions

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt

refactor(Move): Create abstract class MenuFoldersFragment

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/res/layout/bottom_sheet_actions_menu.xml
app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml

refactor(Action): Hide postpone action for v1

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/res/drawable/divider.xml
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/fragment_thread.xml
app/src/main/res/layout/item_bottom_sheet_action.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/view_bottom_quick_action_bar.xml
app/src/main/res/raw/add_padding.css
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Depends on https://github.com/Infomaniak/android-core/pull/33

Revert card style design for messages to a 1px divider

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Sort "ThreadList header fix" code

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Thread: Use `folder` backlink instead of `folderId` to optimize queries

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Message: Use `folder` backlink instead of `folderId` to optimize queries

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/Thread.kt

Clarify Threads creation algorithm

---

app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAdapter.kt

https://sentry.infomaniak.com/share/issue/d3547670cca84a879dc0d610711bde3f/

 Adapter is notified after `onDestroy()` is called

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/res/layout/dialog_report_phishing.xml
app/src/main/res/layout/dialog_with_description.xml

Add Report Phishing action

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt

Fix app crash on reopening logout dialog

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/res/drawable/ic_unknown_user_avatar.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add unknown recipient button when composing new message

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Factorize snackbar in a manager for ease of use

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Sort `customFolders` by name

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

Authenticate API calls to get Avatars

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Order actions

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Refactor `shortUid` use

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt

Copy email address to clipboard

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

Correctly update `unreadCount` of all impacted Folders when receiving new Message

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadResult.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

refactor: move thread to thread package

---

app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/item_recent_search.xml

Add Search history support

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt

Support `swipeRefresh` on Search results

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

Add custom pagination for the Search

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt

- LocalSettings: Add `DEFAULT_RECENT_SEARCHES` value
- FolderController: Clarify `getFoldersQuery()` code
- ThreadController: Rename `apiThreads` into `remoteThreads`
- SearchViewModel: Rename `hasNoNextPage` into `isLastPage`

Small code enhancements upon Search feature codebase

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

Add `searchResults` debounce before calling API

---

app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt

Save `recentSearches` after each new search

---

app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Use localized strings for `notYetImplemented()`

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/color/primary_button_background.xml
app/src/main/res/layout/dialog_input.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Update the folder creation dialog with the maquetted button's color and add error handling by the textInputLayout

Update CreateFolder dialog

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Confirmation dialog when flushing

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

API call when flushing a Folder

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Deleting SearchResults from a newly added account caused an `IllegaleStateException`

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
app/src/main/res/drawable/ic_checkbox_unchecked.xml
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/layout/view_simple_setting.xml
app/src/main/res/values/dimens.xml

Multiselect UI

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/res/layout/bottom_sheet_multi_select.xml
app/src/main/res/menu/main_actions_multi_select_menu.xml
app/src/main/res/navigation/main_navigation.xml

Multiselect Menu bottom sheet

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

Remove `abstract currentClassName`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/main/res/layout/fragment_move.xml

Clean Multiselect code

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt

Update existing `Actions` codebase to handle multiple `Threads` at once

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

`Archive` API call for Multiselection

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

`Favorite/Unfavorite` API calls for Multiselection

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

`Seen/Unseen` API calls for Multiselection

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

`Delete` API call for Multiselection

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/res/navigation/main_navigation.xml

`Move` API call for Multiselection

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

`Spam/Ham` API calls for Multiselection

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt

Add missing Messages during Threads algo

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Override Message `equals()`

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

As Api under 27 doesn't have the possibility to change the navigation button color, we cannot change the Navigation Bar color (it would be white on white colors).

Do not change NavigationBar `color` for API < 27

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Fix some realm accessing with an invalidated or deleted object
Exemple:
```
Accessing object of type Folder which has been invalidated or deleted
```

fix: Some accessing an object invalidated or deleted from realm

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Depends on https://github.com/Infomaniak/android-core/pull/43

Display black colored initials for avatars in dark mode

---

build.gradle

Depends on https://github.com/Infomaniak/android-core/pull/44

Fix kMail `liveData` version

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Depends on #724 
Depends on #755 
Depends on #756 
Depends on #757

Empty States are now correctly shown & hidden

---

.idea/navEditor.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values-v27/themes.xml
app/src/main/res/values/themes.xml
settings.gradle

Depends on https://github.com/Infomaniak/android-core/pull/45/files

Add AppLock feature

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Fix a bug where adding a new attachment was deleting the others

Fix new Attachments overriding old ones

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactChipAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
app/src/main/res/layout/chip_contact.xml
app/src/main/res/layout/view_recipient_field.xml

Replace ChipGroup with RecyclerView using FlexBoxLayoutManager
Depends on #767

Fix Signature being cut off

---

app/src/main/res/layout/chip_contact.xml
app/src/main/res/layout/view_recipient_field.xml

Slightly decrease vertical spacing between chips to match spacing with top divider

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Depends on https://github.com/Infomaniak/android-core/pull/47

Update avatar colors

---

.github/workflows/sentry-release.yml

- Add tag commits in sentry
- Create new sentry release
- Determine the issues and regressions introduced in a new release
- Predict which commit caused an issue and who is likely responsible
- Resolve issues by including the issue number in your commit message
- Receive email notifications when your code gets deployed

feat: Create sentry release for each new tag

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Closes: https://github.com/Infomaniak/android-kMail/issues/790

Fixes SENTRY-109662 (NPE in MainViewModel `forceRefreshMailboxesAndFolders()`)

---

app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Fixes SENTRY-112211
Close #793

fix: Sentry 112211 - Serializer for class 'Any' is not found

---

app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml

This reverts commit 7bf6060f37ccd9aefb5137e17bb12418592199c6.

Revert "Remove dividers between swipe action setting choices"

---

.idea/navEditor.xml
app/build.gradle
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/InformationBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
app/src/main/res/drawable/ic_update_logo.xml
app/src/main/res/layout/bottom_sheet_information.xml
app/src/main/res/navigation/main_navigation.xml
build.gradle
settings.gradle

Depends on https://github.com/Infomaniak/android-core/pull/48

Add "Update available" dialog

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Support system theme in the onboarding except for Lottie

---

app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Depends on https://github.com/Infomaniak/android-core/pull/54
Fixes SENTRY-114084
Fix #825

fix: Not initialized bearer token from services

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
app/src/main/res/drawable/ic_check_rounded.xml
app/src/main/res/layout/item_contact.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Greys out already used emails when auto completing recipients

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt

Depends on https://github.com/Infomaniak/android-core/pull/55

Make contact search accent insensitive

---

app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt

Highlight matched text when adding Contact to an email

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt

- [Fix: Inline not loaded in first load](https://github.com/Infomaniak/android-kMail/commit/ca21b93eb44937ae043412e996f161739cc58f3b)
- Fixes #837
- Fixes #838
- Fixes #839

Fix inline not loaded first time and similar Sentry issues

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt

Add missing `resource` in Attachment when fetching it for a forwarded Draft

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt

Remove `isInMenuDrawer` default value

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/view_recipient_field.xml

Depends on #858 
Depends on https://github.com/Infomaniak/android-core/pull/59

Display loader when opening a Draft

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt

Fields & chevron now correctly collapse/rotate when Recipients are added/deleted

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt

Decrease code complexity in Search

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt

Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/f106f83853f042ab9a09ff3905ee3d1f/

Use `.copyFromRealm()` to fix crash when Contacts are invalidated in Realm

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/res/navigation/main_navigation.xml

Depends on https://github.com/Infomaniak/android-core/pull/61
The duration of the security tolerance timeout can be discussed

Dont lock account switch

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt

Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/d73ba6abb40a4cdda917a73497d18c1c/
Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/f6d5d11f849a451882f26e955aeed99a/

If user tries to `mailTo:` without being connected, redirect to `LaunchActivity`

---

app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt

Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/7c9198d8284d48fb849c9e4f9cbc0c7b/
Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/30c63a33a8524246beff169505a76e16/
Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/bcbf1e65df4e41f6a7698da32812c686/

Add Sentry log + Fix crash when Threads & Messages are in multiple Folders at the same time

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
build.gradle

- Centralize Breadcrumbs usage
- Track Fragments lifecycle
- Track Navigation, with `from`, `to` & `args` data

Add some Sentry logs

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on https://github.com/Infomaniak/android-core/pull/64

Handle emails in the future

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageBodyScaleListener.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageBodyTouchListener.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt

Enables first version of a zoom on emails for the time being

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/dae6cb5d36e14f1c9548824540d17fb3/
Fix #903 
Fixes kmail-android-18

Fix crash if user did twice the same action

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt

Fix Sentry: https://sentry-mobile.infomaniak.com/share/issue/f6d5d11f849a451882f26e955aeed99a/

Fallback on 1st Signature if there is no default one

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

**Changes**
- Notify only once for each group of summary

fix: Several notifications are showed

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
build.gradle
settings.gradle

The new version of realm fixes the "IN" bug
https://github.com/realm/realm-kotlin/pull/1365

Add getThreadsQuery with messageIds

---

app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt

Depends on https://github.com/Infomaniak/android-core/pull/66

Display Quotas in correct unit

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Depends on #915 
closes #916 
Fixes kmail-android-55

Fix `currentMailbox` not selected

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/res/layout/item_thread_load_more_button.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat(ThreadsList): Add "Load more" button

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Depends on https://github.com/Infomaniak/android-core/pull/67

Move lock at app level and not MainActivity

---

app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt

Wipe Contacts BDD to remove all contacts without email

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt

Toggle light and dark display of mails using js instead of reloading all of the mail

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsDeltaResult.kt
app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsResult.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

At 1st opening of a Folder, fetch 500 Messages by batches of 25

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/res/layout/item_thread_load_more_button.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add "Load more" button

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/standard/AndroidManifest.xml
app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt

Rename `ApplicationMain` into `MainApplication`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

App doesn't crash anymore when refreshing Threads without connectivity

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Auto hide/show "Load more" button

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

https://github.com/Infomaniak/ios-kMail/pull/759/

Don't parse oversized emails (like ios)

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

iOS recently changed the limit from 5 to 1, so we changed it here as well to stay synced.

Lower the "Quote size detection" limit to match iOS modification

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt

Add Matomo in DeleteDraft snackbar

---

app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt

Prevent from clicking multiple times a SnackBar action

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_new_message.xml

Snackbars are meant to be inside of CoordinatorLayouts to be swipable, I quickly made the change
Depends on #970

Swipe to dismiss snackbars

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt

Toast for saving and sending drafts from mailto:

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/WorkerUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Snackbar when sending an email

---

app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt

Fixes kmail-android-7b-1573
Fix #1001

fix: Inject AccountViewModel

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

Search: Reorganize `fetchThreads()` code

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

Search: Rename `resourcePrevious` into `isFirstPage`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

Messages from Search are not lost into Realm anymore

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/navigation/main_navigation.xml

Keep Draft data in UI when recreating the Activity

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Update Signatures when updating Mailbox content

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

This PR only shows the snackbar to the user. The feedback for when you come from a mailto: is implemented in a following PR

Notify user of Draft failure to send/save

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Improve Draft send/save speed by returning from Worker before waiting to refresh Draft folder

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt

LoginActivity: Clean both `authenticateUser()` code

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

If needed, switch to `passwordValid` Mailbox, or logout

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Manage locked Mailbox

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Revamp Mailbox error

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt

Leave Composition screen if we can't get Signatures

---

app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Fix #1062
Fixes KMAIL-ANDROID-9Q

fix: Folder realm closed from mainViewModel

---

app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Fix `null` Mailbox after migration

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

Currently, the folder diff is calculated synchronously, which is blocking the ui. To avoid this, we use **AsyncListDiffer** to move everything asynchronously.

feat: Asynchronous load and calculate folders diff

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/AttachmentController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/di/RealmDatabaseModule.kt
app/src/main/java/com/infomaniak/mail/di/RealmQualifiers.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt

Since the mailboxContent needs to be lazy, we need a wrapper.
Fixes #1084, fixes #1083

Fix inject mailbox content

---

app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

NullPointerException when getting completed Draft worker results

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

**Description**
When we create a folder, we receive an exception, so we check each character that is blocking and not optimal.
**Enhancement**
Instead of creating a list for each character and going through the list to check whether the folder name is valid or not, we'll let Realm take care of the folder search so we don't have to do all that, and the search is performed asynchronously. (*Change already made on iOS*)
**Fixes**
Fixes #1098, fixes #1097

Fix create folder

---

app/src/fdroid/java/com/infomaniak/mail/GplayUtils.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/standard/java/com/infomaniak/mail/GplayUtils.kt

We are now ISO with iOS.
Should fix https://sentry-mobile.infomaniak.com/share/issue/023cac333c1447599562130c31f2dd34/ 🤞

Threads are now refreshed once instead of thrice when coming back to app

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

Realm 1.10.0 fix this: https://github.com/realm/realm-kotlin/issues/929

Refactor after fix realm query 'in'

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

Improve search

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

fix: When the search is stopped on return, the data disappears

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt

feat: Init Realm migration

---

app/src/main/res/layout/bottom_sheet_restore_emails.xml
app/src/main/res/layout/fragment_attach_mailbox.xml
app/src/main/res/layout/fragment_invalid_password.xml

Depends on https://github.com/Infomaniak/android-core/pull/73

Fix input layout icon paddings

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Remove unnecessary draft creation

---

app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/res/navigation/main_navigation.xml

Add Notification's Reply action

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationJobsBus.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationPayload.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

Add Archive & Delete actions in Notifications

---

app/src/main/java/com/infomaniak/mail/ui/main/MailboxListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt

Remove ioDispatcher from adapter

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Depends on #1195 
Depends on Infomaniak/android-core/pull/80

Snackbar outside worker

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt

Add snackbar debounce timer when sending to avoid flickering

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt

Fix login fragment manager

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt

fix: Search in local with a quote throw RLM_ERR_INVALID_QUERY_STRING

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt

Fix Signature API error

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Simplify context access in AndroidViewModels to remove duplication

---

app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt

Fix #1230 
Fixes IKMAIL-ANDROID-5R

fix: Network exception from RegisterUserDeviceWorker

---

app/build.gradle

Depends on #https://github.com/Infomaniak/android-core/pull/83
**Changes**
Update `compileSdk` and `targetSdk` to 34

Update navigation to 2.7.0

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
app/src/standard/java/com/infomaniak/mail/di/StandardEntryPoint.kt
app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt

Hilt register user device

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/ExternalContentSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/res/drawable/ic_thread_mode_conversation.xml
app/src/main/res/drawable/ic_thread_mode_message.xml
app/src/main/res/layout/fragment_cancel_delay_setting.xml
app/src/main/res/layout/fragment_forward_mails_setting.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/fragment_thread_mode_setting.xml
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Put back `ThreadMode`

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt

**Feature**
- Update RealmChangesBinding: add AsyncListDiffer support
**Fixes**
- Fix #1244

fix: Inconsistency in adapter with RealmChangesBinding

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Optimize Threads algo

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/NoMailboxActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Fix InvalidMailboxes fetching Activities

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Fix Realm adapters IllegalStateExceptions

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Split `foldersLive` into `defaultFoldersLive` & `customFoldersLive`

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Add Matomo for External Recipient feature

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

fix: Message has empty from from ThreadAdapter

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

Move `FolderAdapter.setFolders()` code to correct dispatcher

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Hilt support for NotificationUtils

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/di/RealmDatabaseModule.kt
app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

feat: Hilt support for mailbox info
fix: https://sentry-mobile.infomaniak.com/share/issue/d665c58014a840c288aac0ae4c541f8f/
Depends on #1309

fix: Multiple instance errors for mailbox info

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Fixes #1318, fixes #1315, fixes #1317, fixes #1320, fixes #1321, fixes #1322, fixes #1323, fixes #1324

Fix a lot of Realm `IllegalStateException`

---

app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

Add a 2 sec timeout in `splitContentAndQuote()`, instead of a 1 Mo limit

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

Correctly select avatar & recipients in ThreadList

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

`fetchMessagesHeavyData()` now returns `uids` of deleted & failed Messages

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Handle deleted Messages

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/res/layout/item_message.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Display error message for failed Messages

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Slightly delay handling of deleted & failed Messages, so there is no race condition anymore in the ThreadAdapter

---

app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Move SplitBody from Body to Message

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/models/AiResult.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/res/layout/fragment_ai_prompt.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Generate AI proposition from prompt

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt

Update AI API call

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/res/drawable/ic_filter.xml
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/navigation/new_message_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

AI display proposition

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/AlertDialogUtils.kt
app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
app/src/main/res/layout/dialog_ai_replace_content.xml
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Insert AI proposition in Body and replace existing one

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt

Cancel AI request when leaving the fragment

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Use `data class` instead of Triple to send data from Thread VM to Fragment

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/AlertDialogUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Delete popup specific behavior

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

AI error messages

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Reduce code complexity

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Fix returned Threads list from Threads algo

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Reduce parameters complexity in `RefreshController`

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Update return type of feature flag API call

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
app/src/main/res/layout/fragment_ai_prompt.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add random AI prompt examples as placeholders

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt

Fix lifecycle handling

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

fix: Split body throw an IllegalStateException sometimes

---

app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt

Various enhancements for Sentry in Notifications

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

Update Sentry level for failed Notifications

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt

Fix LoadMore button blink on first dataset creation

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Update MessageNotFound Sentry

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Fix loader that wasn't disappearing sometimes

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/res/navigation/new_message_navigation.xml

Could be reviewed commit by commit

Add Matomo for the AI feature

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Scroll to correct Message when all expanded Messages are done loading

---

app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
app/src/main/java/com/infomaniak/mail/data/api/UnwrappingJsonListSerializer.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/data/models/message/SubBody.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

Add SubBody in Realm

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt

Display SubBodies

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt

Add Sentry when displaying an Email with SubBodies

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Fix empty backups

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareChip.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareTextInput.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ToggleableTextFormatterItemView.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/layout/activity_new_message.xml
app/src/main/res/layout/chip_contact.xml
app/src/main/res/layout/fragment_ai_prompt.xml
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/view_recipient_field.xml
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/navigation/new_message_navigation.xml

Move `newMessage` package outside of `main` package

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

fix: Deleting an attachment triggers an IndexOutOfBoundsException

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/models/InfomaniakPassword.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt

Login user in kSync

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt

Pop back to ThreadList after SyncAutoConfig is done

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/res/drawable/ic_synchronize.xml
app/src/main/res/layout/fragment_menu_drawer.xml

Add navigation to SyncAutoConfig activity from MenuDrawer

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt

Don't re-synchronize an already synchronized User

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/res/layout/activity_sync_auto_config.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add possibility to install kSync if it isn't already installed on the device

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Handle API errors

---

app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
app/src/main/res/layout/fragment_menu_drawer.xml
app/src/main/res/layout/view_decorated_text_item.xml
app/src/main/res/values/attrs.xml

Put SyncAutoConfig MenuDrawer entry on 2 lines

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncInstallFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
app/src/main/res/layout/fragment_sync_install.xml
app/src/main/res/layout/fragment_sync_onboarding.xml
app/src/main/res/layout/fragment_sync_start.xml
app/src/main/res/navigation/sync_auto_config_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Split SyncAutoConfigActivity into 3 Fragments

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
app/src/main/java/com/infomaniak/mail/views/InformationBlockView.kt
app/src/main/res/color/secondary_text_color_disabled.xml
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/layout/view_information_block.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Please review using whitespace mode for diff

Update AI error design

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncInstallFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
app/src/main/res/layout/activity_sync_auto_config.xml

Add Matomo in Sync

---

app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Split `fetchCredentials()` into more meaningful functions

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Fix already-sync snackbar that wasn't appearing

---

app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncInstallFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt

Check if kSync is up-to-date

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/DiscoveryBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SyncDiscoveryBottomSheetDialog.kt
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values-fr/strings.xml

Add Discovery bottomSheet for Sync auto-config

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Add Data class for the callbacks

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/RoundedBackgroundSpan.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt

Clean code after leaks

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InformationAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/TitleAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

Clean AlertDialogs code

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt

Add matomo events for ai subject replacement dialog

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/res/layout/fragment_intro.xml

Fix Onboarding buttons colors

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/ComposeSubject.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/res/layout/fragment_new_message.xml

SwiftKey was not showing autocompletion results with the previous 'hack'

Fix compose Subject field autocompletion for SwiftKey

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

We now also detect outlook replies again thanks to the modifications
Depends on #1540

Stop detecting simple blockquotes to collapse replies

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Refactor handling of collapsed responses per message of a Thread

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Automatically expand quotes of threads of one message

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt

This reverts commit e70ec0522ea000ea1b7c45130238b8869857bc12, reversing changes made to bc725cca36084721135d888f90d2c185b0a1c83a.

Revert "Merge pull request #1541 from Infomaniak/fix-duplicated-threads"

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt

Delete duplicated Threads after updating all existing Threads

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroPagerAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/RoundedBackgroundSpan.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt

This [comment](https://github.com/Infomaniak/android-kDrive/pull/1123?w=1#pullrequestreview-1734254576) started a conversation with @tevincent & @FabianDevel, and we made a choice!

Unprivate `companions` for the sake of simplicity

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/ai/ContextMessage.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Transforms the message we're replying to into plain text and send it alongside the AI API call so the AI knows some more context on how to reply correctly

AI uses the previous Message as context to be more accurate when answering

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt

Also take subbodies into account when transforming previous message to plain text for the AI API call
Depends on #1554

Factorize `subBodies` fusion

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiSharedData.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Flow for when the user replies to a message too big to be handled by the AI

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
app/src/main/res/layout/item_attachment.xml
app/src/main/res/layout/view_attachment_details.xml
app/src/main/res/values/attrs.xml

Create custom view for attachment

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/PlayServicesUtils.kt
app/src/main/java/com/infomaniak/mail/workers/AppUpdateWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
gradle/libs.versions.toml

Depends on #1563
Depends of https://github.com/Infomaniak/android-core/pull/107

Add worker to update app in background

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/res/layout/fragment_thread_list.xml
app/src/main/res/layout/view_avatar.xml
app/src/main/res/values/attrs.xml

Update touch target of profile button to match specs and be coherent

Make profile button easier to click

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt

T02: Move ThreadListAdapter `formatList()` out of companion

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

T03: Sort Thread code before adding Tablet mode

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
app/src/main/res/layout/bottom_sheet_attachment_actions.xml
app/src/main/res/navigation/main_navigation.xml

Save to kDrive

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/PlayServicesUtils.kt
app/src/main/java/com/infomaniak/mail/workers/AppUpdateWorker.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
gradle/libs.versions.toml

Same as #1590, seems this was not merged correctly in Master
My guess is, it was merged in its parent #1563, at the same time the parent was being rebased on Master, which dismissed the merge of #1590 by pushing the local branch without this merge

Add worker to update app

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

T04: Clean Thread code before adding Tablet mode

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt

T06: Add selection background when clicking on a Thread

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/res/layout/fragment_thread.xml

T07: Display Folder name in Thread empty view

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

T08: Update ThreadFragment toolbar icon when rotating device

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt

T09: Handle back pressed on Tablet mode

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

T10: Close Thread when marking it as read

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt

T11: Close Thread when switching Folder

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt

T13: Update MultiSelection when deleting open Thread

---

app/src/main/res/layout/bottom_sheet_multi_select.xml
app/src/main/res/layout/bottom_sheet_reply.xml

Remove forgotten margin before bottom sheets actions and one forgotten divider

Update small bottom sheets UI oversights

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/res/layout/fragment_menu_drawer.xml

Add transitions in menu drawer

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

T14: Temporary fix of `statusBarColor`

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/values/colors.xml

T15: Tablet easter egg

---

.idea/navEditor.xml
app/src/main/res/navigation/main_navigation.xml

T16: Sort navigation code

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

T17: Remove ugly types (Pair, Triple, etc…) in some LiveData

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

T18: Simplify navigation to Thread

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

T19: Correctly place Snackbar depending on currently displayed fragments

---

app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt

T19.5: Add Avatar easter egg

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/drawable/ic_navigation_default.xml
app/src/main/res/values/themes.xml

T20: Various Tablet improvements

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/AttachmentMimeTypeUtils.kt
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/layout/fragment_menu_drawer.xml
app/src/main/res/layout/fragment_thread.xml
app/src/main/res/layout/item_message.xml

T21: Clean code

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt

Depends on https://github.com/Infomaniak/android-core/pull/115
Depends on #1622

Change values() to entries after kotlin 1.9

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Depends on https://github.com/Infomaniak/android-core/pull/116
Depends on #1622

Try to fix update bug + add lots of logs for debug

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt

Depends on https://github.com/Infomaniak/android-core/pull/117

Transforms shared values util into an interface so we don't need redundant local functions anymore

---

app/src/main/java/com/infomaniak/mail/ui/main/NoAnimSlidingPaneLayout.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/fragment_thread_list.xml

https://github.com/Infomaniak/android-kMail/assets/149579879/33767967-226a-46aa-adfd-23b5723480ab

Remove animation when opening and closing the sliding pane layout

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt

Fix snackbar being displayed too soon with Storage Permission

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Hide Thread `emptyView` sooner so it doesn't blink

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Expires after 6 months of non-use

Unlimited token

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

Click on Avatar now opens MultiSelection

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/res/layout/view_calendar_event_banner.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Some minor UI updates according to new specs

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/res/xml/locales_config.xml

Depends on https://github.com/Infomaniak/android-core/pull/120

fix: select the correct language

---

.github/workflows/android.yml

Like this: https://github.com/Infomaniak/android-kDrive/pull/1172

Improve CI

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

Depends on https://github.com/Infomaniak/android-core/pull/124

Remove unused `Disposable` return value

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt

Implement "Add to calendar" button

---

app/src/main/res/layout/item_message.xml

Fix margins around items inside a thread

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt

Calendar event matomo

---

app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/NavigationExtensions.kt

Move all navigation extensions to own file

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt

Make sure ThreadFragment is displayed after rotation

---

app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt

Replace SharedPrefs by DataStores in Stores module

---

app/src/main/java/com/infomaniak/mail/di/ActivityModule.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt

Depends on https://github.com/Infomaniak/android-core/pull/135

Update Core for Immediate update support

---

.idea/navEditor.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/res/drawable-night/illu_update_required.xml
app/src/main/res/drawable/illu_update_required.xml
app/src/main/res/values/themes.xml
app/src/standard/java/com/infomaniak/mail/firebase/FirebaseApiRepository.kt

Depends on https://github.com/Infomaniak/android-core/pull/136
Depends on #1703

Add update required view

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Depends on https://github.com/Infomaniak/android-core/pull/133

Ignore defaults avatars coming from the API for the User profile

---

app/src/test/java/com/infomaniak/mail/AppVersionCheckingTest.kt

Depends on https://github.com/Infomaniak/android-core/pull/141

Add test for App versions comparaison

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Only display Loader for current Folder

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt

Allow to unfavorite Drafts

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt

depends on https://github.com/Infomaniak/android-core/pull/143

Add `etag` for kMail

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapterState.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Restore Thread state when coming back

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/res/navigation/main_navigation.xml

Optimize opening of Thread to handle both ThreadFragment & PrintFragment

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/PrintHeaderUtils.kt

https://sentry-mobile.infomaniak.com/organizations/sentry/issues/16639/?project=4&referrer=issue-stream&statsPeriod=90d&stream_index=6
Depends on #1724

Fix print not working for empty subject

---

app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Clean code before optimizing ThreadState handling

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Depends on https://github.com/Infomaniak/android-core/pull/145

Remove the `no_avatar_default` choice when getting the profile

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt

UI now correctly updates when marking Thread as seen

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt

depends on https://github.com/Infomaniak/android-kMail/pull/1749
[select_mailbox.webm](https://github.com/Infomaniak/android-kMail/assets/149579879/dc4036d6-5bba-4b76-83b0-c57a9fcbbf73)

Fix wrong selected mailbox

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

Depends on https://github.com/Infomaniak/android-core/pull/147

Fix Attachments not being uploaded when activity is destroyed by system

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt

Fixes MAIL-ANDROID-3E0
Fix #1754

fix: Observe folders throw a Realm IllegalStateException

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/di/ActivityModule.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt

depends on https://github.com/Infomaniak/android-core/pull/156/
[in_app_review_kmail.webm](https://github.com/Infomaniak/android-kMail/assets/149579879/aebefe59-dcbd-469b-bf5a-22fd833657dd)

In-App review in kMail

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt

Move code before Draft revamp

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Save Draft in Realm when leaving NewMessage screen

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Allow to send multiple times the same Attachment + Correctly delete Attachments files

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/res/layout/view_recipient_field.xml

Hide Chevron until Draft loading is finished

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/DiscoveryBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingPagerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/res/layout/cardview_thread_item.xml
gradle/libs.versions.toml

Clean code after Draft revamp

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt

Remove side effects when using Draft object of NewMessageVM

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Remove wrongly added Signature & Quote from Draft snapshot

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Clean code

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Sort NewMessage VM code

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

D1: Prepare to use LiveData instead of Draft model for UI

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/res/navigation/new_message_navigation.xml

D2: `subject` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/navigation/new_message_navigation.xml

D3: `body` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

D4: `quote` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

D5: `signature` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt

D6: `from` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

D7: `attachments` field now uses its own LiveData

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

D8: `recipients` fields now use their own LiveData

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt

D10: Simplify Draft initialization

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt

Lost version: #1800
Depends on #1816

Simplify Draft initialization

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

Fix UI not updating when "Don't keep activities" is enabled

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Shortcut `executeDraftActionWhenStopping()` when going to background without changes

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/res/navigation/main_navigation.xml

Sort & rename Settings in `main_navigation`

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/ui/login/IlluColors.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsMailboxesAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
app/src/main/res/layout/cardview_thread_item.xml
app/src/main/res/navigation/main_navigation.xml

Reformat code

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Also save Draft when going on background or FilePicker or IA

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

Directly upload Attachment when adding it to the Draft

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Depends on #1826 
Replace folder name by their role or id
Replace attachments uris by their localUuid

Remove personal info from sentry

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

- Create new exception to detail bug 
- Hide file name in exception message

Detail attachement bug to sentry

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
app/src/main/res/layout/fragment_signature_setting.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

https://github.com/Infomaniak/android-kMail/assets/149579879/6871edf7-2b90-4fd1-a25a-455430d9a87e

Redirect to webmail signatures settings

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
app/src/main/java/com/infomaniak/mail/data/models/signature/SignaturesResult.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Update signature API to take into account the fact that we can have no default signature.

Update Signature API and handle nullable signature

---

app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Remove useless Sentry scope

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/res/navigation/main_navigation.xml

we should not close multi selection before an action is performed

Fix disappearing multi-select on a single Thread when selecting the "More" action

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt

Depends on https://github.com/Infomaniak/android-core/pull/181
The LoginButton progress was defaulting to `WHITE` color.
It's now using the correct `colorOnPrimary` color.

Send correct color for LoginButton progress

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt

Fixes MAIL-ANDROID-160
Fix #1871

fix: Only retry api calls for the current user 

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Map values should be accessed safely. Using the non-null assertion operator can throw a NullPointerException.

Fix reliability issues

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Updated default value to the more logical one.

The default value of `isThemeTheSame` should be `true`, and not `false`

---

app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Move nested `when` to their own function to enhance readability.

Refactor the code to eliminate this nested "when".

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt

We shouldn't have mutableList as function parameter.

Remove mutable parameter.

---

app/src/main/res/layout/fragment_new_message.xml

Avoids missclicking the close icon instead according to designers

Place information icon of external banner to the left of the banner

---

app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveFragment.kt

Rename FolderAdapter into MoveAdapter

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/res/layout/view_information_block.xml
app/src/test/java/com/infomaniak/mail/AppVersionCheckingTest.kt

Depends on https://github.com/Infomaniak/android-core/pull/198

Format regions

---

app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt

This exception is caused by internet connection probleme or FCM problem, it's not on our side

Do not log FCM exception SERVICE_NOT_AVAILABLE

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Put everything in an extension to easily reuse it across the code. Motivated by the new rich html editor support inside the app

Simplify enabling algorithmic darkening on webviews

---

app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt

I added the lastModified date from cache because it's how it works on our IOS app and some other drive.

Add last modified date in URI when sending attachment to kDrive

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Right now we have a deeper issue with recycling of Threads or with resetPanes() on tablet in landscape. This issue probably causes even more issues in the app that do not crash the app which makes it harder to detect.
This PR at least avoids the crash and tries to gather more info on the source of the issue but the problem persists and needs to be fixed in another PR.

Protect against empty isThemeTheSameMap and add Sentry to better understand the issue

---

app/src/main/res/layout/view_avatar_name_email.xml

Fix bimi out of place certification 

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuFoldersFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/res/layout/fragment_move.xml

Remove NestedScrollView in Move fragment

---

app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Improve Folder sorting

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/UserToBlockAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/UserToBlockBottomSheetDialog.kt
app/src/main/res/layout/bottom_sheet_user_to_block.xml
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

https://github.com/user-attachments/assets/00bd6614-2c4b-42dc-9b68-48069cad7a61
https://github.com/user-attachments/assets/56945401-1b82-4d7e-bbd4-90365a3d74f1
https://github.com/user-attachments/assets/6157246e-f726-4d43-bca8-c6718ad9821d

Adapter to block a specific contact in a thread

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/res/raw/editor_style.css

Make the rich html editor's color follow the theme of the app
Depends on #1958

Update caret color of the rich html editor

---

app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapterCallbacks.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/EmptyFoldersViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/FoldersHeaderViewHolder.kt
app/src/main/res/layout/item_menu_drawer_footer.xml

Organize MenuDrawer Adapter's code

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Before:
https://github.com/user-attachments/assets/6b4ab193-98a9-4d23-80af-3a600dda462b
After:
https://github.com/user-attachments/assets/3379b67c-db78-4b76-bd04-de68b186604a

Do not send blank characters to AI services since it does not handle Blank characters well

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Variables renaming

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/getMessages/ActivitiesResult.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

Fetch Messages by Date (instead of UID) when going through Folder's history

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/utils/SentryRealmLogger.kt

We added Realm informations in Breadcrumbs.
They are going wild !!
Breadcrumbs are unreadable now :(
This PR is trying to calm them down a little.

Calm down Realm breadcrumbs

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Catch exception in uploadStatus getter and add info for sentry

---

app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/res/layout/cardview_thread_item.xml

https://github.com/user-attachments/assets/c78b66d5-2b83-443e-8112-559a952e38aa

Add specific UI for thread when in SPAM folder

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/AccountManagementSettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/AccountManagementSettingsViewModel.kt
app/src/main/res/layout/fragment_settings.xml

Depends on https://github.com/Infomaniak/android-core/pull/227
https://github.com/user-attachments/assets/f7570ff4-fd21-4258-9fd2-75ac12f415db

Logout user properly when this one has been deleted

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt

This was asked in order to give more importance to the infomaniak contacts

Give priority to autocompleted api contacts over phone contacts

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Replace Realm `writeBlocking` by `write` in MailboxController `updateMailbox(…)`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

Replace Realm `writeBlocking` by `write` in ThreadController

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt

Replace `map { … }.toSet()` with `mapTo(mutableSetOf()) { … }`

---

gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/android-core/pull/232

Bump Libs & Core

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AccountBottomSheetDialog.kt
app/src/main/res/layout/activity_main.xml

feat: Put back missing Halloween easterEgg

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt

Depends on https://github.com/Infomaniak/android-core/pull/240

fix: Stop using strings reflection to get suffixes for Nougat and after

---

app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesViewModel.kt

chore: Clean code

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

Depends on https://github.com/Infomaniak/android-core/pull/247

fix: API errors

---

.gitignore

Depends on https://github.com/Infomaniak/android-core/pull/256

refactor: Remove `app` dependency in `Core`

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt

Depends on https://github.com/Infomaniak/android-core/pull/269

feat: Add support for login sso

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

This will be needed for the snooze feature but it can first be refactored on master directly

refactor: Avoid duplicating values when defining what folders need to refresh together

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/MailDateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/PrintHeaderUtils.kt
app/src/main/java/com/infomaniak/mail/utils/date/DateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt

Take this opportunity to also better name some of the MailDateFormatUtils methods

fix: Fix hardcoded 24 hour format

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/date/DateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt

Some places need to display the year, so I made a logic to only show it when the displayed date is on a different year. This will also be needed for the snooze feature

feat: Display year date when the date is on another year

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/api/CalendarRealmInstantSerializer.kt
app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AccountBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/RestoreEmailsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/date/DateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Depends on https://github.com/Infomaniak/android-core/pull/290

feat: Use new DateUtils in Core

---

app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt

Depends on https://github.com/Infomaniak/android-core/pull/293

refactor: Use correct version of FormatterFileSize

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

To reproduce: Respond to your own mail and spam the **chip** with your name.

fix: Remove assert not null when it's not needed

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

feat: Handle signatures containing `+xxx` in the answering email

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/UserToBlockAdapter.kt

feat(Matomo): Add tracker for block user dialog events

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt

Depends on https://github.com/Infomaniak/android-core/pull/303
Depends on #2213

feat: Matomo my kSuite

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/AttachmentUploadStatus.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/DraftUtils.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

refactor: Rename `AttachmentUpload` statuses

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/InboxRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/ScheduledDraftRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt

refactor: Extract each RefreshStrategy to its own file

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt

feat: Don't forget to create a new Thread if we receive a snoozed Message for the 1st time

---

app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt

With cache: 
https://github.com/user-attachments/assets/f6549d3b-1145-459c-9cba-8fa8fcae3a4a
Without cache: 
https://github.com/user-attachments/assets/ce185564-cf1d-4df2-bdf4-a90275cd6680

feat: Enable cache of WebViews

---

app/src/main/java/com/infomaniak/mail/ui/main/settings/KSuiteDashboardFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt
settings.gradle

Depends on https://github.com/Infomaniak/android-core/pull/315

feat(MykSuiteInitials): Add initials to myKSuite avatar

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/api/HeadersSpamBooleanSerializer.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/SenderDetails.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/SendersRestrictions.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Headers.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/res/layout/dialog_select_date_and_time.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

* Message considered as Spam  
* Not in the Spam folder  
* Anti-spam filter disabled  
* Sender **not** approved  
* Message considered as Spam  
* Not in the Spam folder  
* Anti-spam filter enabled  
* Message considered as **not** Spam  
* **In** the Spam folder  
* Sender blocked  
* Message considered as Spam  
* Not in the Spam folder  
* Anti-spam filter enabled  
* Sender approved

feat: Add Spam banner

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Factorize the impacted folder computation (and include the snooze folder in it) and remove intermediate `unsnoozeThreads` method exposed through SharedUtils.
The SharedUtils method was just splitting half of the result's handling in a method while the other half was handled later on. Now everything is handled at the same place
Depends on #2289

refactor: Remove unnecessary intermediate method that split logic in another file

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

feat: Add snooze api calls success snackbars

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/res/layout/bottom_sheet_multi_select.xml

feat: Add snooze actions in multiselect bottom sheet

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt

If a migration fails, instead of blocking the user on an unusable app until he uninstalls it and reinstalls it, we can do it for him while keeping him logged in.
To do so, we delete the realm that caused an issue and reboot the app. We need to make sure this never occurs but this is a last resort solution.
If an error is thrown, it will still be logged to Sentry so we can fix it and when in debug mode the error will continue to visually render the app unusable as usual so developpers are not tricked by this safeguard.

feat: Drop db and reboot the app when realm migration failed

---

gradle/libs.versions.toml

Depends on https://github.com/Infomaniak/android-core/pull/335

chore: Bump Libs & Core

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/WindowInsetsExt.kt
app/src/main/res/layout/fragment_thread_list.xml

feat: Better edge-to-edge management from the threadlist and menudrawer

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/res/layout/fragment_search.xml

feat: Add support for edge-to-edge in SearchFragment

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/WindowInsetsExt.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_no_mailbox.xml
app/src/main/res/layout/activity_no_valid_mailboxes.xml
app/src/main/res/layout/fragment_ai_engine_choice.xml
app/src/main/res/layout/fragment_ai_prompt.xml
app/src/main/res/layout/fragment_ai_proposition.xml
app/src/main/res/layout/fragment_intro.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_new_account.xml
app/src/main/res/layout/fragment_sync_onboarding.xml

Depends on https://github.com/Infomaniak/android-core/pull/342

feat: Sdk 35 secondary activities

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/ThemeSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Depends on https://github.com/Infomaniak/android-core/pull/344

refactor: Bump kMail to minSdk 24

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/res/layout/fragment_new_message.xml

This code is useless now hat we implemented the scheduled feature by another means

chore(EditorAction): Remove oxbow code "clock action"

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

As observed by @sirambd, some places in the code can try to access realm values when the realm has been closed and therefore trigger crashes

fix: Prevent crashes when switching users and trying to access values on a closed realm

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/annotations/TestOnly.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/data/models/SwipeDisplayBehavior.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/FolderRoleUtils.kt
app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
app/src/test/java/com/infomaniak/mail/FolderRoleUtilsTest.kt
app/src/test/java/com/infomaniak/mail/dataset/DummyFolders.kt
app/src/test/java/com/infomaniak/mail/dataset/DummyMailboxContent.kt
app/src/test/java/com/infomaniak/mail/dataset/DummyMessages.kt
app/src/test/java/com/infomaniak/mail/dataset/DummyThreads.kt
gradle/libs.versions.toml

fix: Make `getActionFolderRole()` use the correct Folder in all cases

---

app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/view_encryption_lock_button.xml
app/src/main/res/values/attrs.xml

feat(Encryption-04): Add unencryptable recipients with encryptionButtonView

---

app/src/main/java/com/infomaniak/mail/Clicks.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/ScheduleDraftResult.kt
app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailViewModel.kt

refactor: Clean code

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/main/settings/KSuiteDashboardFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt

Depends on https://github.com/Infomaniak/android-core/pull/417

chore: Bump Core

---

app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt

Depends on https://github.com/Infomaniak/android-core/pull/420

fix: User avatar

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt

Clean code by regrouping the places where encryptionStatus is set into one mediator

feat(Encryption-10): Use mediator to update encryption status

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionActionsBottomSheet.kt

The regex wasn't capturing correctly number > 9

fix(EncryptionRegex): Fix bold argument

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/utils/AvatarTypeUtils.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
settings.gradle

Depends on https://github.com/Infomaniak/android-core/pull/437

feat: Separated avatar data computation from display

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/AddReactionChip.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/icons/FaceSmileRoundPlus.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/icons/Icons.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
EmojiComponents/src/main/res/values-de/strings.xml
EmojiComponents/src/main/res/values-es/strings.xml
EmojiComponents/src/main/res/values-fr/strings.xml
EmojiComponents/src/main/res/values-it/strings.xml
EmojiComponents/src/main/res/values/strings.xml
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

Add the "add reaction" button component to the emoji reaction module
Depends on https://github.com/Infomaniak/android-kMail/pull/2386

feat: Add reaction button

---

app/src/main/java/com/infomaniak/mail/ui/main/emojiPicker/EmojiPickerBottomSheetDialog.kt

This reverts commit aaaac265b89742f2bc3e8d80911366ea2fb6e88f.
This commit got merged by error during some rebases

chore: Revert "fix: Force bottom sheet as fullscreen to fix issue of cropped bottom part of the emoji recyclerview"

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/AccountManagementSettingsFragment.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

chore: Revert "Use preprod URLs"

---

app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

depends on https://github.com/Infomaniak/android-core/pull/457

fix: Add logs when an error occured on Login and Account Creation webview

---

app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

refactor: Use BuildConfig URL instead of hardcoded one in Extensions.kt

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

fix: Fix empty Draft auto-saving when they shouldn't

---

app/src/main/java/com/infomaniak/mail/data/models/message/FormatedPreview.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Clean emoji reaction preview and add api to reuse it for ThreadList
|  Before  |  After | 
|---|---|
|  <img width="1080" height="2400" alt="Screenshot_20250916_093330" src="https://github.com/user-attachments/assets/a6ac14c6-ccd6-4838-8a0d-ae20f0f8ebac" />  |  <img width="1080" height="2400" alt="Screenshot_20250916_152208" src="https://github.com/user-attachments/assets/62ad82c8-0b83-49b3-aff1-ff5daa05c276" />  |

feat: Format reaction notification

---

app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadMessagesProgressDialog.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExt.kt

Depends on https://github.com/Infomaniak/android-core/pull/536

refactor: Renamed `goToPlayStore()` into `goToAppStore()`

---

app/src/main/java/com/infomaniak/mail/MailUrls.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Depends on https://github.com/Infomaniak/android-core/pull/537

chore: Uniformize `/` in URLs usage
