Infomaniak/android-kMail

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

**Fixes**
> The expedited work before android 31 it creates services in the foreground and this is not what we want here
> Otherwise the service may be called back several times
> Since the service can be in background, we don't want it to be dependent on the realm of the app, because it can create problems when the app is closed
> Need some modifications in `Core` to allow exceptions to be thrown from the `ApiController` whenever desired.

Improve Draft actions worker

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

**Enhancements**
- Start the SyncMessagesWork with an initial delay
- Avoid to launch the work if it's unnecessary, It happens especially when you change user

Start sync worker with delayed duration and Avoid launching the work when it is unnecessary

---

app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

When an email has no subject, the string is supposed to be `null`.
But sometimes the string isn't null, instead it's empty _(for example, when sending the email via Gmail)_.
Depends on #403

Set Message' subject at `null` when empty

---

app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

**Fix**
When clicking on a notification it was always the same sender request in the notification `pendintIntent`, so when clicking it was always the last update of the `pendingIntent` that was used

fix: not redirected to the right email notification when there is many

---

app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt

**Description**
Currently it is realm that takes care of updating our ui.
But there are some cases where we have realm changes but we don't want the ui to be updated.
**Fix**
This solution adds a feature that will prevent `RealmChangesBinding` to check if the content has really changed before notifying by overriding the `areContentsTheSame` method from the adapter

RealmChangesBinding can now check if the content has been changed in the ui

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt

-  [fix: forceRefreshMailboxes not stopped while it's cancelled](https://github.com/Infomaniak/android-mail/commit/cbbce24b04d95557fe3faa8aa427c071df673081)
- feat: [add coroutine scope utils](https://github.com/Infomaniak/android-mail/commit/cf43800232b266796abcec2db51b894b7876ae92)
**Exception**
```
io.realm.kotlin.exceptions.RealmException: [7]: Accessing object of type Mailbox which has been invalidated or deleted
at io.realm.kotlin.internal.CoreExceptionConverter$initialize$1.invoke(RealmInteropBridge.kt:119)
at io.realm.kotlin.internal.CoreExceptionConverter$initialize$1.invoke(RealmInteropBridge.kt:118)
at io.realm.kotlin.internal.interop.CoreErrorConverter.convertCoreError(CoreErrorConverter.kt:27)
at io.realm.kotlin.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUti …
```

Fix force refresh mailboxes when cancelled

---

app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

fix sentry https://sentry.infomaniak.com/share/issue/fd357ea10c0f4ce891480b989d44688c/
**Description**
> Apps that target Android 12 (API level 31) or higher can't start foreground services while running in the background, except for [a few special cases](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions). If an app tries to start a foreground service while the app runs in the background, and the foreground service doesn't satisfy one of the exceptional cases, the system throws a [ForegroundServiceStartNotAllowedException](https://developer.android.com/reference/android/app/ForegroundServiceStartNotAllowedException).
https://developer.android.com/guide/components/foreground-services#background-start-restrictions

fix: ForegroundServiceStartNotAllowedException

---

app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

Fix sentry https://sentry.infomaniak.com/share/issue/c814b67d1e2343728dcf34a02dbfadfa/
```bash
io.realm.kotlin.exceptions.RealmException: [6]: Realm accessed from incorrect thread.
at io.realm.kotlin.internal.CoreExceptionConverter$initialize$1.invoke(RealmInteropBridge.kt:119)
at io.realm.kotlin.internal.CoreExceptionConverter$initialize$1.invoke(RealmInteropBridge.kt:118)
at io.realm.kotlin.internal.interop.CoreErrorConverter.convertCoreError(CoreErrorConverter.kt:27)
at io.realm.kotlin.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUtils.kt:24)
at io.realm.kotlin.internal.interop.realmcJNI.realm_get_value(Native Method)
at io.realm.kotlin.internal.interop.realmc.realm_get_value(realmc.java:650)
at io.realm.kotlin.internal.interop.RealmInterop.realm_get_value-Kih35ds(Realm …
```

fix:  setPreviousMessage in draft with incorrect thread

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

`markAsReadUnread` for a Message now correctly closes the BottomSheetDialog
`markAsReadUnread` for a Thread now pop to the entry before ThreadFragment (could be ThreadListFragment or SearchFragment)

Fix `markAsReadUnread` back navigation when closed

---

app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt

It happens that the currentUser is null, but it is quite normal since it is a constant

fix: current user is null

---

app/src/main/res/raw/add_padding.css

Especially visible in very short messages without signatures

Fix missing bottom margin

---

app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

**Fix**
Replace all excess spaces with a line break
**Screenshot**
**Result after fix**

fix: Remove multiple whitespaces

---

app/src/main/res/values/styles.xml

TextEdit's copy and paste pop up was inheriting dialog background color which cause an ugly white square behind the popup

Fix ugly background of Copy/Paste popup

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt

**Features**
- feat: Add an utility to separate the message and its history [MessageBodyUtils.kt](https://github.com/Infomaniak/android-mail/compare/split-body-history-from-message?expand=1#diff-592fa659ebf4dff67cd29f268e4b6358f1a46c2dd270ffad58abbbb4ec154bda)
- feat: Only show body messages for notifications

Split Body history from Message

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

- [fix: Webview download inline attachment several times](https://github.com/Infomaniak/android-mail/commit/ef6429b29951aee819a396abb3e7a4472e78e43b)
- [fix: Always display inline attachment if a cache file exists](https://github.com/Infomaniak/android-mail/commit/286e8e3fe60fe03047fa3f7c2747417e18b9f6ea)

Fix webview display inline attachment

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/res/layout/item_message.xml

WebView in dark mode did not have the correct color #121212 instead of #101010

Fix WebView's `backgroundColor` in dark mode for `text/plain` when displaying Message

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt

When booting the app with empty realm, the unread chip was displayed when it should not have

Fix unread chip visibility when LiveData's value is null

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/res/layout/item_detailed_contact.xml
app/src/main/res/layout/item_message.xml

* Fix margin below Detailed Informations of a Message.
* Fix margin above Body of a Message.
* Hide `To:` field in Detailed Informations when it's empty the same way it was already done for `Cc:` and `Bcc:`.
* If a name is too long to fit on a single line and needs to be wrapped, left align the name rather than horizontally center it.

Mail detailed informations UI fixes

---

app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

- feat: Known errors management, which will make the service always restart them

Handle Draft actions API errors

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

With stable ids:
[Stable ids.webm](https://user-images.githubusercontent.com/28200274/228893957-06ce9256-a199-4963-868f-abb6db8b7587.webm)
With DiffUtils
[With DiffUtils.webm](https://user-images.githubusercontent.com/28200274/228895045-408ff144-cc98-40ad-adb5-a2783d4587c1.webm)

fix: The `swipeRefresh` layout lags too much in Threads list

---

app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt

Fix crash in `computeInitials()` if Correspondent has only ponctuations in its name

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt

- Fix #831
- [fix: Update the folders of a realm already closed](https://github.com/Infomaniak/android-kMail/pull/832/commits/9eafe7fa4c9425397e65b509b1abc1dce1b804b4)
**Before fix**
[Menu with bug](https://user-images.githubusercontent.com/28200274/229840519-23e9c655-fbab-4080-b0cf-90b9ca16bcba.webm)
**After fix**
[menu without bug.webm](https://user-images.githubusercontent.com/28200274/229841179-53bb3929-4604-41b2-b02a-d0f8b220be47.webm)

Fix issue 831 - IllegalArgumentException: Tmp detached view should be removed from RecyclerView 

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt

Stop requesting notif permissions if the user has manually disabled it by any means.
Fix bug where permissions are not requested for Api < 33

Stop notif permission requesting

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt

- [fix: Download manager for api below 29 need write permission](https://github.com/Infomaniak/android-kMail/commit/42a9a681ade9222522ff0e4859eb5768c94e2dfd)
**Stacktrace**
```
java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/kMail-attachments-2023 0407 Article DauBé supplém.zip: Neither user 10176 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
at android.os.Parcel.createException(Parcel.java:1966)
at android.os.Parcel.readException(Parcel.java:1934)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
at …
```

fix: DownloadManager for API below 29 need write permission

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

`IllegalArgumentException` when navigating from Thread fragment to DownloadAttachment dialog

---

app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/workers/BaseProcessMessageNotificationsWorker.kt
app/src/standard/AndroidManifest.xml
app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
app/src/standard/java/com/infomaniak/mail/StandardApplicationMain.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

**Changes**
ApplicationMain has been separated, so that each flavor can do its processing in its own applicationMain instance
- fix: fdroid flavor with hilt
- fix: draft injection with hilt

fix: Application with hilt doesn't work in fdroid flavor

---

app/src/main/res/layout/item_message.xml

Setting the default style attribute to 0 solves the problem

Fix longpress on webview that makes the recyclerview jump on ThreadFragment

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

I did not undo the rendering modifications to redo them because it increased the code complexity but did not seem to grant any speed increase compared to a simple load or reload

Use `reload()` when changing screen size to rerender emails instead of `loadUrl()`

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

This modification decorrelates the toast from the actual saving of the data in realm for now. But in the next PR, the save will happen right there in the `onStop()` which will make it so the toasts makes sens again

Now displays the missing "saving draft" toast when putting the app in the background

---

app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

* Reuses the same draft id instead of creating a new one each time
* Only show the toast or the snackbar when modifications happened
Depends on #1007

Fix draft saving when putting app in the background

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

If we don't expand it, it will stay shrunk when entering a new folder. If the folder is empty, we cannot scroll so it will stay shrunk for ever in this folder

Expand the fab when we enter a folder

---

app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

A bug is remaining but we can't do anything about it : if the network is sufficent for a  send or save request to reach the server, but too weak to bring us the answer without a timeout, we don't have data to delete or update a draft. 
So it will be re-send or saved multiple times
Depends on #1052

Fix Draft with bad connection

---

app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt

Switching to an account with only one mailbox would display the mailbox switcher with this mailbox, because of a query that would be trigger with -1 (for the current mailbox) as exceptedIds. Thus the true currentMailbox would not be excluded and the observe would think there is more than 1 mailbox.
To fix this, we need to change the currentMailboxId before reloading the app, so the mailbox query won't be triggered with -1

Fix mailbox switcher bug when only 1 mailbox

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt

Most of the realm problems we have are due to the fact that we close the realm a little before switching accounts, so the coroutines in progress often come up against exceptions.
Realm instances are now managed differently to ensure that we only close instances when the new account is started.

Improve Realm usage

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt

When you leave the app and come back very quickly, the realm instance isn't closed yet, so we'll reuse it as long as we can.

fix: Problem when returning to the app

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

We make sure to close realm cash only when we're sure everything's finished, based on the global ViewModel

fix: Realm is still in operation even though it is closed

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

**Fix all known bugs and improved research**

Fix search v3

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt

**Fix**
After an update, if the user was in the search, and the data has been deleted, then the search opens but crashes because the files have not yet been loaded.
Fixes IKMAIL-ANDROID-J9
Fix #1136

fix: SearchAdapter has not been initialized

---

app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt

**Fix**
Actually It's possible to return to the launch before it's finished.
**Solution**
After starting the destination activity, we run finish to make sure we close the launchScreen, so that even when we return, the activity will still be closed.

fix: It's possible to return to the launch

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

When starting a Search, if the ThreadsAlgo is currently running, we cancel it to avoid overlap with Realm writings.

Cancel ThreadsAlgo in Search

---

app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt

Because Jsoup used to pretty print all of the HTML, the `wholeText()` method believed some of the tabs of the pretty print to be spaces. It added unwanted spaces at the start of each HTML tag, especially visible when using the webmail WYSIWYG because it wraps most lines inside a `<div>`.

Fix HTML interpretation when editing a Draft

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt

**Description**
Sometimes notifications don't work because they're based on the application token, which is only available when the app is foreground, but if you're in the background you may not get the current user info.
**Fixes**
- Now we avoid using the current user's token, but just pass him his own `httpClient` so we don't have to worry about it.
- In a second step, we reset the notification in case of error, as a temporary solution (see if you want to do it differently).

fix: Notification actions doesn't work sometimes

---

HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt

A not so uncommonly occurring issue with our mail rendering is that some really wide continuous lines of text (mostly URLs) are not softwrapped correctly. This results in excessively zoomed out emails which become hard too read or even completely unreadable for the most extreme cases. 
This PR solves this issue by adding "zero width spaces" inside long strings which will enable softwrapping at these key positions. This strategy is inspired by what Google seems to be doing in its webmail and it seems very likely to also be the comportment they have on their mobile app.

Improve email rendering by breaking wide lines

---

app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt

Use `<wbr>` instead of zero width spaces because they do not get copied to the clipboard and do not interfere with URL detection by the Android system when selecting a url inside plain text

Fix render long lines for selection or copy

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardHeaderManager.kt

Cleaning this code up made me realize how little our processing of emails' html is centralized. This needs to be fixed in a following PR. We access the field `value` from `Body` objects way too often when we never should access it raw like this but rather have the final html be:
* created with subbodies 
* wrapped if it was a text/plain
* sanitized
This result should be the only value we ever access
Depends on #1602

Extract reply/forward header creation code in their own use case file

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt

As explained by the webmail team, we can remove these values
Depends on #1603

Remove class and id that were copied from the webmail but are actually useless

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/main/java/com/infomaniak/mail/views/itemViews/AvatarMergedContactData.kt

AvatarView automatically updates its avatars rather than relying on parent fragments to relay the information up to each AvatarView when a new mergedContactDictionary is obtained

Simplify and lower coupling of updating AvatarView avatars

---

app/src/main/java/com/infomaniak/mail/views/BottomSheetScaffoldingView.kt
app/src/main/res/layout/bottom_sheet_actions_menu.xml
app/src/main/res/layout/bottom_sheet_attachment_actions.xml
app/src/main/res/layout/bottom_sheet_detailed_contact.xml
app/src/main/res/layout/bottom_sheet_information.xml
app/src/main/res/layout/bottom_sheet_junk.xml
app/src/main/res/layout/bottom_sheet_multi_select.xml
app/src/main/res/layout/bottom_sheet_restore_emails.xml
app/src/main/res/layout/view_bottom_sheet_scaffolding.xml
app/src/main/res/values/attrs.xml

Makes creating new bottom sheets faster, easier and less error prone.
It helps avoid forgetting some parameters when creating new bottom sheets. Also fixes the way we scroll elements inside the bottom sheet, the handle should always stay on top (this especially makes sens when you think about the handle becoming a button when in accessibility mode). Helps make the bottom sheet title coherent across bottom sheets by being defined in a single place. 
The title feature only starts being used in the next calendar PR but this already lays the ground for that next PR

Create a common bottom sheet scaffolding

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

To simplify future addition of navigations from the ThreadFragment, all the variables and methods that had to be created are now simplified in a single `safeNavigate()` method that works just like the one in any other Fragment

Expose similar `safeNavigate` method in ThreadFragment as other fragments have

---

app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt

 Do not display bottomsheet if user already went by himself  in onBoarding

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEventResponse.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
app/src/test/java/com/infomaniak/mail/ExampleUnitTest.kt
gradle/libs.versions.toml

The only way to have a not too ugly result was to handle the user's status change locally and not fetch the API to not trigger the adapter and bind the whole message again causing it to blink after each click.
This also means that right now, after the user has replied and left the thread, if he loses his internet connexion and comes back in the thread, the status of the user will be the one we had inside Realm when he last opened the thread and not the one he answered with. I think that this can be considered uncommon enough to let it slide
---
Nevermind, the adapter now detects if only the attendance state of attendee have changed and if so, only the precise UI elements associated to this get to bind instead of the whole message
Depends on #1670

Add possibility to reply to calendar events

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/Extensions.kt

Lock MenuDrawer in ThreadFragment

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt

https://github.com/Infomaniak/android-kMail/assets/149579879/3550ffdb-e712-45c6-a233-6662168b560f

Deactivate multiselect if we don't have any selected mail

---

app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/res/layout/item_message.xml
app/src/main/res/layout/item_super_collapsed_block.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Depends on #1706
Depends on #1683
Depends on https://github.com/Infomaniak/android-core/pull/125

Add SuperCollapsedBlock

---

app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt

The id we used to detect outlook blockquotes is not enough. The div with this id only contains the header of the reply/forward but the content of the body of the previous email is right next to this div, at the same level as the div and was therefore not detected.
Instead of half detecting outlook blockquotes, don't detect anything for now until we truly detect them correctly

Stop detecting outlook blockquotes

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Remove duplicated Draft folder refresh

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Fix print feature not working on SuperCollapsedBlock Message

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

Opening a Thread now correctly marks it as read

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/MailboxExternalMailInfo.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt

Use `externalMailInfo` API call instead of `mailboxes` one to get ExternalMail info

---

app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

We don't have much information on the sentry, and I haven't managed to reproduce it, but I've fixed a case that's close
Fixes MAIL-ANDROID-6PV
Fix #1756

fix: MenuDrawer throw an IllegalStateException

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt

Fixes MAIL-ANDROID-3SZ
Fix #1752

fix: MessageWebviewClient throw an IllegalStateException [RLM_ERR_INVALIDATED_OBJECT]

---

app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

This was never triggered so it's safe to remove it

Remove unused sentry

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt

The SingleLiveEvent is now a MutableLiveData because we want it to trigger when the Activity is recreated, so the chevron's visibility will be correctly computed.
Depends on #1766

Correctly trigger Chevron visibility updates

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

Issue can be seen in sentry issues like the id 41593

Fix a crash when an Email's body in a Notification had too many characters

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt

If the device has GooglePlay services, we refresh every 4 hours. Otherwise, every 15 minutes. We also dismiss notifications of messages we've read on another device.

Change mail periodic refresh condition & dismiss notifications of already read messages

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

We were notifying twice the Adapter when removing an Attachment, so the animation was cancelled.

Put back missing animations when removing Attachments

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

We were saving Draft everytime we add or remove an Attachment, it's too much.
Now, we only save Draft when adding an Attachment.
Also, if we add a lot of Attachments at the same time _(via the FilePicker)_, and we delete them all while it's still saving, the DraftsActionsWorker will fail because it's won't find the files on the phone disk.
Now, it will just ignore these failures so the Draft can be saved.

Only save Draft when adding Attachment

---

app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt

The click listener of a thread was recycled without being updated if the thread doesn't have any from Recipient
The Sentry also wasn't useFul as it is normal that a thread can have an empty from (a draft for example)

Fix clickListener not being recycled correctly if thread doesn't have sender

---

app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt

Depends on https://github.com/Infomaniak/android-core/pull/173
Since Android O, Google decided to use SI format (1000) instead of binary one (1024) to display bytes.
Source : https://stackoverflow.com/a/3758880
Unit tests are here : https://github.com/Infomaniak/android-core/pull/175

Use custom FormatterFileSize

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt

Code was split apart for no reason

Put ThreadList adapters initialisations together

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

The Intent.Send action should normally not be used to write mailto according to the doc.
However, some apps do it, and it is supported by gmail.
So to avoid suffer from the comparison, we now support it too.

Support `mailTo` from `Intent.Send`

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt

We don't want to send Sentry about NetworkException.
So we make sure that when we send a Sentry about an Exception, it's not a NetworkException.

Don't log NetworkException in Sentry

---

app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt

There is a weird OOB issue in NotificationManagerCompat, so we are trying to thread-protect the MutableMap by using a ConcurrentHashMap instead.

Use `ConcurrentHashMap` instead of `mutableMapOf` for `notificationsByMailboxId` to fix OOB

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Since `v1.2.4`, there is no more Sentry about _"Should display threads is true but there are no threads to display"_, so we can remove this comment.

Remove comment about old "Should display threads is true" bug

---

app/src/main/AndroidManifest.xml

On Chromebooks :
The app will boot even if there's no touchscreen.
The app will automatically resize itself at boot to be in landscape and fullscreen.

Chromebook : various improvements

---

app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt

Depends on #1865
Depends on https://github.com/Infomaniak/android-core/pull/183
Depends on https://github.com/Infomaniak/android-core/pull/184
When going to the Login WebView, then coming back to LoginFragment, the LoginButton color was reset to the default PINK theme.

Send current textColor to `initProgress()` so it'll be able to restore it when progress is done

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt

Depends on #1873
Some functions in Realms controllers that are using a given Realm are not in the companion.
Shouldn't they all be in it ?

Move some Realm functions to Controllers' companions

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt

We receive a null pointer exception, in some cases the reference no longer exists.
Fixes MAIL-ANDROID-ASQ
Fix #1879

fix: KotlinNullPointerException form Base

---

app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt

Return a copy of the list instead of the reference to avoid crash if this list is modified by another threads.

---

app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

We were trying to get the `AccountUtils.currentMailboxEmail` too early when creating the NewMessageActivity via shortcuts.
Instead, we are now using the `currentMailbox.email` that is already available.
Fixes MAIL-ANDROID-ASZ

Fix NPE when getting email in `getDummySignature`

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt

`throw IllegalStateException("")` can be simply written as `error("")`.

Replace this throw expression with error("").

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt

Set manually the 'has_attachments' while loading heavy data, this fix is temporary and will be remove when the API returns the good value.
The value return by the API for the lite version of the message is sometimes false, the API can return that they're are attachments but actually not and it can occurred in the two way. The API will probably be fixed but not soon.

Temp fix attachments

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEventResponse.kt
app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt

The previous condition wasn't really needed and in veeeery extrem case might even have been wrong. This PR makes it so the detection logic is inline with iOS and the web

Fix calendar event canceled detection

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapterCallback.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Depends on #1875
Sometimes, we display an empty Thread in the ThreadsList.
The cause isn't known yet, but in the meantime we just delete them in Realm.
It's possibly because we are out of sync, and the situation will resolve itself shortly.

Delete Thread in Realm if it's empty and we're trying to display it in ThreadsList

---

HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/EmailContextualMenuAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt

Split this XXX characters long line (which is greater than 130 authorized).

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/res/layout/fragment_move.xml

Remove the nested scrollView, and merge the 3 recycler views into only 1.
Also, the MoveFragment is no longer a `MenuFoldersFragment`, it's only a `Fragment` now.
In the end, the `MenuFoldersFragment` will probably be deleted.

Nested #1: Remove NestedScrollView in Move fragmentes

---

app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

All Sentries about failed notifications are merged into one.
It's hard to really see what's happening.
The reason will now be in the Sentry's message, so we'll have 1 different Sentry by reason.

Remove `reason` in `sendFailedNotification()` to dissociate Sentries

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

We have Messages with several parent Folders, which shouldn't be possible.
For example, we have Messages that are in the same time in INBOX & Trash, or INBOX & another Folder.
Non-exhaustive list of other Folders :
- Trash
- Drafts
- Promotions
- Social networks
- Custom folders that are children of INBOX.
- probably more…
This Sentry is here to check if the issue comes from the API.

Add Sentry to check if the API can send us a Message from another Folder

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

We already have the info we need, no need to fetch them again from the LiveData.

Move the access of `uiAttachments` liveData to `updateDraftAttachmentsFromLiveData()` parameters

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/DraftExtensions.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Depends on #1923
Replace `Attachment.uuid` usage with `Attachment.isAlreadyUploaded` when possible
Replace usage of `uploadLocalUri` with `localUuid` when possible

Simplify Attachment IDs usage

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Sending the Sentry about orphan Drafts is nice, but if we don't delete them… They'll just keep sending Sentry that we are already aware about, until the end of times.

Delete Drafts orphans after sending the Sentry about them

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Some user have the banner saying the WebView is outdated. Adding a sentry to understand what we have as version will help to understand the problem.

Add Sentry to check if the WebView version name is well formatted

---

app/src/main/res/layout/fragment_new_message.xml

Color was white on a light yellow background in dark mode. It's an oversight when replacing the TextView with a MaterialButton, I've put back the old textColor

Fix external banner text color in dark mode

---

app/src/main/java/com/infomaniak/mail/data/models/Bimi.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

When we received a Bimi, we displayed it automatically.
But we should only do that if we can't find an avatar.

Reduce Bimi priority (it should only be displayed if we couldn't find an avatar)

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

The avatar image was sometimes wrong when recycling because when it was a Bimi the currentCorrespondent value was not set to null.

Fix Bimi when recycling

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt

The methods showProgress() and hideProgress() keep crashing on many occasions despite our best efforts to do things correctly. This PR uses showProgressCatching() and showProgressCatching() to avoid crashing
Depends on https://github.com/Infomaniak/android-core/pull/201

Prevent showing and hiding progress crashes by using showProgressCatching() and hideProgressCatching()

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

When editing a draft of mimeType "text/plain", we save the draft with the same mimeType (i.e. text/plain) even if we send a content representing a text/html which completely breaks the draft's content.
This PR forces the mimeType to text/html which is what we always send

After editing text/plain drafts save them as text/html which was missing

---

HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

Previously, sanitization using Jsoup would output a html document with one body nested inside another for no reason. To fix this and output clean code after sanitization, remove one of the two extra bodies if we detect this exact situation

Remove nesting of bodies when sanitizing html

---

app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

The error was:
Error: Must be one or more of: PendingIntent.FLAG_ONE_SHOT, PendingIntent.FLAG_NO_CREATE, PendingIntent.FLAG_CANCEL_CURRENT, PendingIntent.FLAG_UPDATE_CURRENT, PendingIntent.FLAG_IMMUTABLE, PendingIntent.FLAG_MUTABLE, PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT, Intent.FILL_IN_ACTION, Intent.FILL_IN_DATA, Intent.FILL_IN_CATEGORIES, Intent.FILL_IN_COMPONENT, Intent.FILL_IN_PACKAGE, Intent.FILL_IN_SOURCE_BOUNDS, Intent.FILL_IN_SELECTOR, Intent.FILL_IN_CLIP_DATA [WrongConstant]
return PendingIntent.getActivity(appContext, requestCode.hashCode(), intent, pendingIntentFlags)
But pendingFlags was a constant based on API version so Lint was throwing an error.

Update gradle to 8.7 and plugin gradle to 8.5.0

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

This is to avoid a huge amount of Sentry logs (`We received a Notification, but we failed to show it`) when we try to refresh an unopened mailbox.

Check before trying to refresh messages for a specific mailbox if this one has already been open once

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

This sentry is useless because it is a totally normal case. 
You can trigger it by opening a message on the webmail before the notif was fetched

chores(Sentry): Remove useless Sentry

---

app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/res/layout/view_avatar_name_email.xml

Before
After 
The problem comes from `android:layout_weight="1"` that was not updating after recycling.

Fix cut name

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt

Closes MAIL-ANDROID-331
https://sentry-mobile.infomaniak.com/organizations/sentry/issues/15856/
This seems like a very odd case, when the adapter itemCount is not synchronized with the recyclerView children count
As it is rare, not that important and doesn't seem to be caused by a bigger flow, I just added the null Check

Fix uncatched NPE in RecipientFieldView

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Sadly, I couldn't find a way to redirect to the Huawei AppGallery in case the Huawei WebView is outdated. So we are only checking the WebView version of Google WebViews.

Changing the way we log the version of WebViews and also handling only official WebViews from Google

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt

When returning from filePicker, if the activity got recreated the editor toolbar would have been displayed under the keyboard.

Fix the Editor toolbar displayed under the keyboard

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
app/src/main/java/com/infomaniak/mail/utils/JsoupParserUtil.kt
app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Add sentry logs to record memory consumption by jsoup parsing and the method splitContentAndQuotes()
Example usage:

Log jsoup parsing ram usage

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt

In #1990 we tried logging all Jsoup.parse but this one was missing from the PR

Add memory usage logs around a Jsoup.parse that was missed

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/HtmlUtils.kt

If we want to remove cids contained in the quote, we can simply remove it like this.
This way, when forwarding an email with inline attachments, if we remove the forwarding block, we also discard its associated inline attachments

Remove associated inline attachements when removing quote

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapterCallbacks.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/ActionViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/ActionsHeaderViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/FolderViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/FoldersHeaderViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/FooterViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/InvalidMailboxViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/MailboxViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/items/MailboxesHeaderViewHolder.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/res/layout/item_menu_drawer_action.xml
app/src/main/res/layout/item_menu_drawer_actions_header.xml
app/src/main/res/layout/item_menu_drawer_footer.xml
fastlane/metadata/android/fr/changelogs/1_04_002_01.txt

Depends on #1989
In the MenuDrawer, the animation when expanding/collapsing AdvancedActions was missing.
We moved the Actions to their own item in the RecyclerView, so we can have the animation back.

Menu drawer actions as items

---

app/src/main/java/com/infomaniak/mail/views/AvatarView.kt

It happens quite often that the app crashes because of the observeForever in AvatarView.
Fixes MAIL-ANDROID-55P, fixes MAIL-ANDROID-DG5, fixes MAIL-ANDROID-D2W, fixes MAIL-ANDROID-E08

fix: App crashes because of AvatarView

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/move/MoveViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

We don't need the Messages when displaying Folders in the MenuDrawer, so we remove them, because it can be a pretty big list causing OOMs.

Remove Messages from Folders in MenuDrawer

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt

depends on https://github.com/Infomaniak/android-core/pull/208
https://github.com/user-attachments/assets/1eb2241f-ea3b-4972-b787-61d69e60bc36

Use the new networkstatus flow to know if we have internet or not

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

When switching account, we were cleaning RefreshController callbacks, and by doing so we are cleaning the `onStop` callback of the currently executed RefreshController, leading to the impossibility for the RefreshController to call its `onStop` callback.

Fix infinite refresh loading of Threads when switching Account/Mailbox

---

app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt

On Web and iOS it's 2 so we have the same behavior.

Change minimum length of search query

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

We were looping in Kotlin instead of doing a simple Realm query.

Optimize `getThreads()` query when executing action on Threads/Messages

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/SnackbarManager.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Depends on #2005
We can't send more than 1000 UIDs to the API, they will be refused.
So we batch them.

Batch API calls when there is more than 1000 UIDs

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt

https://sentry-mobile.infomaniak.com/organizations/sentry/issues/83172/?project=4&query=is:unresolved&statsPeriod=7d&stream_index=3

Avoid logging to Sentry when we have a network exception

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

There is a Sentry issue saying that we get Messages from the wrong Folder when we refresh Folders.
Can't see why for now, but it seems we get the wrong Folder ?? There is an issue with the folder ID.
This PR is trying to make sure we use the correct Folder so we get the correct Messages.

Make sure we use the up-to-date version of Folder in RefreshController

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ConfirmationToBlockUserDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/UserToBlockBottomSheetDialog.kt
app/src/main/res/layout/dialog_confirmation_to_block_user.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Block with only one sender in thread:
https://github.com/user-attachments/assets/8ce52f34-65ff-4b48-a422-8746bd400b5b
Block with multiple senders in thread:
https://github.com/user-attachments/assets/37502f0b-58d2-448a-9af2-ff08a27a1eda

Add Dialog to confirm we want to block a user

---

app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

addUpdateListener being java code sometimes makes it so the thread of the callback is not the main thread anymore which prevents us from modifying the UI and crashes the app. This makes sure we are on the main thread when calling the callback that will apply the colors and handle UI in general

Fix animated toolbar crash

---

app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

This code was forgotten and is not needed anymore since we changed the way the sending/saving confirmation snackbar is displayed

Remove now unused DraftActionsWorker setProgress

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Most of the sentry issues we receive regarding corrupted attachments come from drafts stored in DB that are retried everytime the worker is started. This bug was caused by the UploadStatus crash inside addDraftBreadcrumbs() for certain. I suspect that there might remain other reasons for the corrupted attachment bug because even with the UploadStatus' runCatching() I did reproduce the corrupted attachement bug once. Also the issue did exist before the addDraftBreadcrumbs() addition and hasn't yet been fixed.
The plan of this PR is to remove the drafts that will never be processed so they stop spamming Sentry. Once this goes live we can see the errors where the attachement is corrupted for another reason than UploadStatus and fix this as well

Delete draft that cannot ever be sent because of corrupted attachments

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareChip.kt
app/src/main/res/layout/chip_contact.xml

Delete recipient backspace wasn't working anymore from API 34, this PR fix it.

Fix using backspace to delete recipient on API 34+

---

app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt

It's been decided to give a higher priority to the api contacts avatar rather than the phone's one

Prioritize api contacts avatar over phone contacts avatar

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

- Marked as read/unread/favorite/unfavorite
- Update locally immediately
- Make WS call
- If there's an error, reset to previous value
- Move/Delete
- Create a local variable in Realm (isMovedOutLocally) and if it is being moved, set this value to true without waiting for the API to return. When displaying the ThreadList, filter on isMovedOutLocally == false
- If there's an error, return as before

Execute actions right away instead of waiting for API call result

---

app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt

This reverts commit 6af361f05efaf8973a80b23dad2ce3923b1a0576.
The task wasn't to do this but to change the order in which contacts are ordered when searching for contacts when writing an email

Revert "Prioritize api contacts avatar over phone contacts avatar"

---

app/src/main/res/layout/view_avatar.xml

This issue occurs with BIMIs avatar that use transparencey. Previously the background of the avatar was set to colorPriamary which clashed with some avatars' colors that where too close to the priamryColor. Setting it to white seems to be the way to go, how BIMIs where thought out

Set avatar background color to white so transparent BIMIs are displayed correctly

---

app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt

It spams sentry just to trigger because _uploadStatus is an empty string

chore(Sentry): Remove sentry of _uploadStatus that is useless

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt

fix: DownloadAttachmentProgressFragment lifecycle crash

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/main/java/com/infomaniak/mail/utils/WebViewVersionUtils.kt

When resizing the mail with js, after zooming, it can still scroll. Sometimes, the issue is caused because the target width in which we want to the fit all of the html is 0. In this case, no amount of processing will ever let us fit the content in a width of 0 obviously.
This PR adds a new clarifying sentry captureMessage to try and understand how we could possibly end up with a target width of 0 in the first place. This PR also adds a tag to the already existing captureMessage to understand in what proportion the issue is caused by zero-width webviews

Add some sentry to better understand message display improvements that still leave some overscroll

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

In the situation of a Thread long enough so we display the SuperCollapsedBlock :
- When clicking on the SCB, we have to display all remaining Messages.
- Instead of displaying all of them in one go, we loop them and send them 1 by 1 every few milliseconds.

When expanding a long Thread, display Messages by batches so it doesn't freeze the UI anymore

---

app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

When a Mailbox isn't attached to a User anymore, we need to update Realm to reflect this.
It's already done when starting the app, but it wasn't done when fetching Notifications in background.

fix: Refresh User & Mailboxes before fetching Notifications

---

app/src/main/java/com/infomaniak/mail/data/api/UrlTraceInterceptor.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt

Add the http response code to the Sentry breadcrumb that logs every api call so we can better understand what happened when an error arises. 
Also make sure that even if the code crashes inside one of the other interceptors, the breadcrumb will still be added

Add api response code to api call sentry breadcrumb

---

app/src/main/res/values/colors.xml

The color token was based on a wrong spec. We just noticed the issue, so here is the update color token with the correct value

Fix coral light color token

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareChip.kt

The issue was that we couldn't delete a recipient chip using the backspace key when composing an email on API 34 and above. To address this, we initially added the `onFocusChanged` method in `BackspaceAwareChip` and set `focusableInTouchMode=true` in the XML layout file for `BackspaceAwareChip`. While this resolved the issue, it caused an ANR on some devices in unknown condition. 
Ultimately, we found that setting only `focusableInTouchMode=true` in the XML was sufficient to fix the problem.

fix: Remove onFocusChange in BackspaceAwareChip

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt

Do not allow the user to add a contact with an invalid email, and set only one entry as 'ContactChipAdapter' for easier management.

fix: Don't show the contact if the email is incorrect

---

app/src/main/AndroidManifest.xml

This is useful to be detectable when another apps want to find all emails app on the phone without using a mailto: protocol or sending any other kind of data to the app

feat: Add APP_EMAIL and DEFAULT category to the main activity in the manifest

---

app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

This will signal to the OS that we want it to run ASAP

fix: Mark the ProcessMessageNotificationsWorker as expedited

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt

fix: Delete Attachment in Realm when we delete it while writing a mail 

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

We can already add these fields on master even if we don't use them yet. And it especially helps split the ApiEnum logic in its own PR. Also avoid having to carry a bump of realm schema version in a feature branch which will constantly need to be updated.
Depends on https://github.com/Infomaniak/android-core/pull/283

feat: Add the new snooze api field to the Message model

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/DateDisplay.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
app/src/main/res/layout/cardview_thread_item.xml

The scheduled threads need to have a new relative formatting of the date which was missing in the original scheduled message feature. This PR adds the missing formatting and lays the groundwork for the snooze as well.
The existing default case logic for formatting dates has simply been moved to the new DateDisplay class without modifications. The name of the XML ImageView holding the "scheduled" icon has been renamed with a more neutral name to easily be reused for snooze

feat: Add missing schedule date format in ThreadListFragment

---

app/src/main/res/layout/dialog_select_date_and_time_for_scheduled_draft.xml

This goes in its own PR because the changes would be lost if they go inside the whole dialog refactor

refactor: Hide schedule time picker cursor and remove unused hint space

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
app/src/main/res/layout/dialog_select_date_and_time_for_scheduled_draft.xml

The error message sometimes not block the user when it should've or it would would block the user when it should not have. The values inside the time picker would also sometime be wrong and have a different one than the one displayed inside the dialog

fix: Select date time dialog wrong values and wrong error messages

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/res/layout/dialog_select_date_and_time_for_scheduled_draft.xml

Simplify some of the logic by removing unnecessary logic
Depends on #2170

refactor: Remove unused values in SelectDateAndTimeForScheduledDraftDialog

---

app/src/main/res/drawable/ic_scheduled_messages_small.xml
app/src/main/res/layout/item_message.xml

Before:
After:
Depends on #2183

chore: Better align expeditor name, schedule date, and icons

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
app/src/main/java/com/infomaniak/mail/utils/MyKSuiteUiUtils.kt
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/navigation/new_message_navigation.xml
gradle/libs.versions.toml

This fix the Release build compilation error by navigating by deeplink from the App to the module's view.
This is needed because in release, the generated args class will be generate 2 times so it will crash compilation. 
And we can't directly use ID navigation as the id of the module's view will not be available from the App.
Source: https://developer.android.com/guide/navigation/integrations/multi-module#across

fix(MyKSuite-09): Fix upgrade bottomsheet nav

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

This will be useful when abstracting logic for the snooze feature

refactor: Decouple impacted folder ids computation in thread algo deleted uids handling

---

app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadMessagesProgressDialog.kt
app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt

Depends on https://github.com/Infomaniak/android-core/pull/302

refactor: Move `goToPlayStore()` from Legacy to new Core

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt

This reverts commit a1c6b848a68cdc9845b097f1baa697a41fff0af1, reversing changes made to dcafc655bcfa1a1cae12e0a7a3451124574d9d8e.
Right now on the very rare occasion where you have a thread composed of messages where messages don't reference all of the other messages of the thread, the fetch algorithm will crash.
This PR reverts the PR that introduced the bug so we keep master clean and we can add the reverted code in a futur PR as the same time as the fix

fix: Revert "refactor: Tidy up `createNewThread()` (#2228)"

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/models/SnoozeState.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

This PR simply computes the snooze state at the thread level and can directly be merged inside master as it's not even visible to the user.
Depends on #2232

feat: Compute snooze state in thread

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt

Queries different threads in realm to choose what threads will be part of the snooze folder and the inbox folder. To do so, I introduce a RefreshStrategy so multiple folders can define different logics for the same step of the refresh algorithm.
This will also help us easily keep track of what bit of logic is different for the snooze folder if the API ever sends us more normal data for the snooze folder
Depends on #2220

feat: Filter snooze in folders

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt

refactor: Extract `handleAddedMessage` into its refresh strategy

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ImpactedFolders.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Defines the custom logic to handle deleted uids for the snooze folder. It leverages the RefreshStrategy to define the custom logic.
Inside this PR there's an issue where the snooze folder is not refreshed after an action on a message. This is fixed in the very next PR.
Depends on #2234

feat: Introduce custom logic to handle deleted uids in the case of the snooze folder

---

app/src/main/java/com/infomaniak/mail/utils/SaveOnKDriveUtils.kt

When saving an email to kDrive, we check if the app is installed on the device. To know that the app is not installed, we need to catch a NameNotFoundException. This is an expected behavior and doesn't need to be logged to sentry

feat: Do not log NameNotFoundException to sentry when saving to kDrive

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

The snooze folder needs a new order for its threads, I took this opportunity to centralize and make it easily parametrisable.
For the snooze folder, not only did I need to change the order from the default descending order to an ascending order, but I also needed to sort by another property of the Thread model.
The goal is to have the Threads that will first be unsnoozed at the top of the screen
Depends on #2239

feat: Custom folder sorting can be parametrized easily for any folder role

---

app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt

If we are the real Me, directly return `true` without computing the plus Me.

refactor: Small `isMe()` optimization

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

fix: Correctly update Message fields

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/SnackbarManager.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Don't forget to refresh the snooze folder after an action has been triggered on an inbox message. By default, this wasn't working because it wasn't ever expected that message with a uid of a folder might want to refresh other folders.
Also, do we want to rename variables of the new ImpactedFolder type?
Depends on #2236

feat: Refresh snooze after action

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt

Now that the snooze folder is correctly fetched and updated, we can hide the folder when there's no message inside it, as intended.
Depends on #2225

feat: Hide empty snooze folder

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/InboxRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt

refactor: Clean code

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

Receiving, updating or deleting a thread from Snooze can impact threads where the processed message is only refrenced as  a duplicate. So we need to recompute theses threads as well in this case
Depends on #2243

feat: Also recompute duplicated threads when snooze message is added/updated/deleted

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt

FolderSort and RefreshStrategy are very similar and should both be accessed through the Folder class instead of choosing a random default value somewhere in the code for custom folders. 
Also RefreshStrategy can be defined inside FolderRole the same way we define FolderSort. This will also avoid computing the `when` every time.
Depends on #2244

refactor: Make property access coherent and go through Folder

---

app/src/main/java/com/infomaniak/mail/data/models/Folder.kt

The internal date represents the date the draft has been created at and not the date at which the draft will be sent. The scheduled drafts folder needs to sort messages by the date they will be sent at with the most recent one at the top of the list

fix: Scheduled message's sorting order

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/InboxRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt

Introduces the naming concept of "twin folders". They are folders where their thread dependant properties need to be recomputed together when one of them changes.

refactor: Simplify and make code more readable

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Folder.kt

Motivated by the change request of the first part of the snooze PR
Depends on #2259

refactor: Turn refresh strategy and folder sort getter methods into property methods

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

This PR required to modify the code that deletes empty threads inside `recomputeThread()` because modifying a snoozed thread by, for exemple, reading it would trigger a `recomputeThread()` which would instantly delete the opened Thread.
In the search, some threads (such as threads from the snooze folder) won't have any messages with the same folderId as the thread folderId. This is an expected behavior and we don't want to delete it this case. We just need to fallback on the last message of the thread when looking for the `lastMessage`.
This reproduces some of the logic of iOS. We keep the same logic we always had if we're not from the search but we can fallback on `messages.lastOrNull()` when we're on a thread from the search. Threads from the search are expected to not always have …

fix: Display snoozed threads as such in the search

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

We were sorting the realm query by `displayDate` which is a method and therefore caused the sorting to crash. Now we define `displayDate` directly inside realm like iOS.

fix: Define displayDate in realm so we can query on it

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt

It will be reused for snooze as well, but I can already put this in its own PR on master
Depends on https://github.com/Infomaniak/android-core/pull/314

refactor: Rename mail const defined in core with a more generic name

---

app/src/main/res/navigation/main_navigation.xml

The dialog is defined twice in two navigations (main and new message), then a Dialog uses the generated navarg class to access arguments, but one of the two navigation definition was missing an argument present in the other. This led to the app sometimes (but not always?) not building

fix: Add missing navargs definition that, only sometimes, prevents build

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/Snoozable.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt

This PR reproduces the hack that the webmail has to do to let snoozed threads with new messages be unsnoozed and reappear in the inbox.
When refreshing folders, we need to detect snoozed threads that have their last message belonging to inbox not snoozed. This state is the state we need to fix, by making an "unsnooze" api call so the thread will come back into inbox.
If the api doesn't lets us unsnooze this specific uuid, the thread could be detected on every refresh and try to be unsnoozed forever, so we take the party to manually unsnooze it and its snoozed messages in the database in this strange case.
Also, the migration for `isLastInboxMessageSnoozed` might be overkill, initializing to `false` would only mean that existing threads in this very rare state won't be automatically …

feat: Unsnooze messages and threads on the api when they receive a new message

---

.idea/navEditor.xml
app/src/main/java/com/infomaniak/mail/MatomoMail.kt
app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ImpactedFolders.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/BatchSnoozeCancelResponse.kt
app/src/main/java/com/infomaniak/mail/data/models/BatchSnoozeUpdateResponse.kt
app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeCancelResponse.kt
app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeResponse.kt
app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeResult.kt
app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeUpdateResponse.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForSnoozeDialog.kt
app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SnoozeBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/Utils.kt
app/src/main/res/navigation/main_navigation.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

This PR adds the possibility to click on the "modify" button of the snooze header in a thread.
This required to reuse UI related to the picking of a scheduled date and factorizing some logic with the "cancel snooze" action
Depends on #2283

feat: Bind modify button of the snoozed thread header

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Later, the MainViewModel methods will be called by multiple fragments, but the error display can be handled once for all calling places if handled inside the view model. This PR moves the snackbar displaying code to the MainViewModel methods
Depends on #2287

refactor: Display snackbars directly from viewmodel so it's centralized for each calling place

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/ConfirmationPopupExt.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/NavigationExt.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Executing one of these actions on a snoozed email will automatically unsnooze the thread on the api. We want to warn the user before he does it.
Depends on #2292

feat: Add confirmation popup on delete/move/archive actions on a snoozed message

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/res/layout/view_message_alert.xml

Actions should not be accessible when not in the snooze folder or inbox. This also applies to the thread header that I missed till now. This PR hides the buttons in this case.

feat: Hide snooze actions in the thread header like the webmail does when not in snooze folder

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt

Right now unseenMessagesCount is accessed a lot of times and I need to slightly alter its behavior in another PR. Yet most access are simply made in order to determine if the thread is in a read or unread state. I expose a `isSeen` property to split and factorize this concern in the new property. The name of the property is the same as for a Message.

refactor: Expose a `isSeen` property for a Thread instead of accessing `unseenMessagesCount` everytime

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt

When migrating with a schema version inferior or equal to 22, during the 22th migration, the field `originalDate` of the new object is set but this field doesn't exist in the latest version of the model's schema anymore as of today. Trying to `set()` this non existing field crashes. Another crash occurs when trying to read `snoozeAction` that never was initialized.
There is no efficient and generic solution with a low memory footprint that can provide a permanent safeguard against this issue, while remaining transparent during migration writing.
Instead, the fix safeguards this very specific case of the error that's been raised and observed in production.

fix: Avoid realm migration crash when setting originalDate or reading snoozeAction

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

To do this, we need to compute the `isSeen` status of a thread by taking into account the duplicates as well. This will also make this `isSeen` computation behavior ISO with the webmail and threads returned directly by the API through the search.
When opening an unread thread, we need to read any message or duplicate that's unread. Not just messages and their associated duplicates.
Snooze folder used to be the only folder that would recompute threads where duplicated messages appeared but now that recomputing a thread requires to look at duplicated messages to compute the thread's `isSeen` property, it is always required for any folder to always recompute threads where duplicated messages appear.

feat: Remove the snooze status of an "unsnoozed" thread when reading it from any folder

---

app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForSnoozeDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

According to the specs, the button's text should adapt between "confirm" and "modify" depending on if we're snoozing a thread for the first time or if we're modifying an already existing thread. This PR makes the modification to follow the spec

feat: Adapt text between confirm/modify depending on the type of snooze action

---

app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt

Reasons to display the generic new mails notification :
- No userId in Notification
- No mailboxId in Notification
- No messageUid in Notification
- RefreshThreads failed
- No Message in the Thread
- Created Notif: no Mailbox in Realm
Reasons to not display anything :
- Mailbox doesn't exist in Realm
- Message is already in Realm
- User disabled Notifications
- The user never opened this Mailbox
- The user never opened this INBOX
- When we fetched Messages, we didn't find any new Message
- Message has already been seen before receiving the Notification

fix: Display generic new mails notification less often, and send some missing Sentry logs

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

This code was used twice in two different places and will soon be used again in a new place, so I extracted it in a function so it's only defined once

feat: Know if the snooze feature is available in current state with a single function

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt

Without specifying currentClassName, the code works perfectly well.
Also remove an unused injected variable

refactor: Remove unnecessary currentClassName

---

app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
app/src/main/java/com/infomaniak/mail/data/models/SwipeAction.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSettingsFragment.kt

I'll need to customize this class and to avoid to make it too big I would prefer to move it to its own file outside of LocalSettings. It already does quiet a bunch of things and LocalSettings might already not be the better place to store it.
I made no code modification, I only used the Android Studio extraction feature

refactor: Extract SwipeAction enum to its own file

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

The wording of the positive button was modified from "confirm" to "modify" when modifying an existing schedule for a snoozed message but the same logic wasn't applied to the scheduled draft. This fixes it

fix: Use the correct wording when modifying the scheduled date of a draft

---

app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt

Recomputing a thread would not compute correctly any value that depends on the computed `lastMessage` variable (i.e. `internalDate` and `displayDate`). This PR fixes the issue so future recomputations are correct and we trigger a migration so we can recompute existing threads.

fix: Fix thread ordering

---

app/src/main/java/com/infomaniak/mail/data/models/SwipeAction.kt
app/src/main/java/com/infomaniak/mail/data/models/SwipeDisplayBehavior.kt
app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapterCallbacks.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/res/drawable/ic_close_small.xml
app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Adds the snooze swipe action. The snooze swipe action is only enabled in the inbox and snooze folder, if your message display mode is set to threaded messages and if you have the snooze feature flag enabled. This required me to add a mechanism to easily define what swipe action can be displayed in what circumstances.
When an action is not accessible in a certain situation, it shows as a greyed out action. When swiped all the way an informative snackbar clarifies even more that the action is incompatible.
I'm not certain about some of the namings, if you've got better ideas I'm all ear.
Sonar rightfully detected that the method that performs swipe actions' logic has too much cognitive complexity, but to not make it harder to review, I fixed it here instead: …

feat: Snooze swipe action

---

app/src/main/java/com/infomaniak/mail/ui/main/folder/PerformSwipeActionManager.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt

Sonar notified us that this method had too much cognitive complexity, but to not make the other PR noisy, I fixed the cognitive complexity here instead.
It also removes 100+ lines from the already very big ThreadListFragment, so it's an even better refactor.
Depends on #2332

refactor: Extract swipe action performing logic to its own file to reduce cognitive complexity

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt

If the device's date was in the past, the unsnoozed date might have been displayed using the relative formatting instead of the default one. This fixes the issue forever.
This occurs if unsnoozed message's date is later than the device's date, which is possible if the device's date is in the past.
Bugged diplayed relative date:
Correct default formatting for dates in the future:

fix: Unsnoozed date display when device's date is in the past

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeResponse.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Make it so calling reschedule of snooze or unsnooze api calls for a single snooze calls the single item route instead. Calling the single item route is the only way to receive api errors from the api to be able to display them to the user.
Also translates new errors introduced with the snooze feature

feat: Display and translate snooze api errors

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt

This reverts commit 2b3c45ec5ad897f2c9605999a48be84d7dc8baf7, reversing changes made to a5388aa3bd69f03db870790241f73dd86d416680.
When you have a long thread with multiple messages in it (mine had 8), when you expand all messages, some of them do not display their content anymore since the fix introduced in PR #2330.
There isn't much info on what that fix was supposed to fix but it broke something even more important maybe.

fix: Revert "fix: Clean view holder in ThreadFragment when view is recycled to avoid crashes (#2330)"

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt

Was previously called for no reason even when no uids were deleted

perf: Do not call recomputeTwinFoldersThreadsDependantProperties when nothing has changed

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/RestoreEmailsBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExt.kt

I bumped core to use the updated translateError() message and took this opportunity to update the usages of `translatedError` inside of mail because they weren't too hard to replace.
Depends on https://github.com/Infomaniak/android-core/pull/340

feat: Replace deprecated translatedError and use updated translateError()

---

app/build.gradle
gradle/libs.versions.toml

It required to use desugaring for the updated java api as explained in their patch note

chore: Bump playServices library

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadResult.kt
app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt

Some folder name tags were missing from the search when fetching API threads on some occasions and they were always missing from the local realm search. This PR fixes this issue by introducing some shared Thread processing between the API and Realm searches. The shared processing is only comprised of the folder name computation for now.
To put this processing in common, I had to move around some of the current processing. I managed to regroup all search threads processing in the same SearchUtils file. I also decoupled the place where threads state is processed from the place where threads are saved to Realm as "search results"

fix: Add missing folder name tags in search results

---

app/src/main/java/com/infomaniak/mail/ui/main/search/NamedFolder.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt

When a search thread has a remote folder id of "inbox" and is snoozed, we need to alter the displayed origin folder name in the search to display "snooze" instead. Snoozed folders are always located inside of inbox, therefore only deriving the displayed origin name from the remote folder id is not enough because of snooze.
Depends on #2347

feat: Display messages coming from the snooze folder as such in the search

---

app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt

Some adresses with special characters such as `'` would not be considered valid on Android but they are indeed valid on web or iOS. Here the code is modified to use the same valid email regex as iOS
Depends on https://github.com/Infomaniak/android-core/pull/365
Depends on https://github.com/Infomaniak/android-kMail/pull/2367

fix: Detect more valid email adresses

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt

This logic was too highly coupled which made it very hard to make the changes I needed for the reaction feature. This refactor removes the `reassignMessagesLive` and `reassignThreadLive` and replaces them with flows for each value

refactor: Remove "reassign" methods and use single centralized flows to handle message logic

---

app/src/main/java/com/infomaniak/mail/data/models/SwipeAction.kt
app/src/main/res/layout/fragment_swipe_actions_settings.xml

There are 2 distinct words to indicate that the swipe action is defined as None and that there is no swipe action defined.

fix: Different word for no swipe action and no choice of swipe action

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt

We were replacing all of the existing threads with the new page instead of merging them together which lead to some threads having no more parent folders. This occurred only for threads that were not already downloaded in the app prior to searching. Other threads would have lost the search folder as a parent folder but they still had their original folder which hid the issue in this case

fix: When fetching more than one search page, add new page to existing threads

---

app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt

Returning a Result.failure() when an api call for a draft has failed would prevent appended works to be run but receiving an error for some drafts should not prevent other appended works from running.
This becomes especially important in the emoji reactions feature when it becomes easy to enqueue multiple works back to back

fix: Return Result.success() inside DraftActionsWorker

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
app/src/main/res/layout/fragment_new_message.xml
app/src/main/res/values/attrs.xml

Depends on #2459 
Clean the code that was aiming to instanciate this view as chips, but is finally not used
Add a delay before displaying the loader to avoid having it blinking when we open a draft

feat(Encryption-09): Clean encryption lock button view and add delay to loader

---

app/build.gradle
app/src/main/java/com/infomaniak/mail/ui/components/MailBottomSheetScaffold.kt
app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt
app/src/main/res/layout/view_bottom_sheet_scaffolding.xml
app/src/main/res/layout/view_bottom_sheet_separator.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

This new compose scaffold recreates the exact style of the mail bottom sheet but in compose. This compose version of the scaffold is needed to correctly handle nested scrolling with new compose components. This will notably be used for the emoji reactions feature

feat: Create a compose mail bottom sheet scaffold to contain future compose code

---

app/src/main/java/com/infomaniak/mail/MainApplication.kt
app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt

Only init and start to collect the currentUserIdFlow when needed
Depends on https://github.com/Infomaniak/android-core/pull/427

fix: Make available the current user token on first login

---

app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt

- Parallelize the calls to the api to check if email are encryptable because it can only take 10 email per call or return error
- Also check locally if the emails are hosted by classic infomaniak domains to avoid calls to the api
Depends on #2452

feat: Encryption support more than 10 recipients in one check

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/ThreadRecomputations.kt
app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
app/src/main/java/com/infomaniak/mail/data/models/SwipeAction.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/AvatarTypeUtils.kt
app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
app/src/main/java/com/infomaniak/mail/utils/FeatureAvailability.kt
app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
app/src/test/java/com/infomaniak/mail/dataset/DummyThreads.kt

When a reaction message targets an existing message, it needs to not display and not be taken into account in some places in the code.
To hide the messages we don't want I replaced accesses to `Thread.messages` that should only consider a subset of messages with the method `getDisplayMessages()` that will adapt and return the correct list of messages everytime it's called.
Depends on https://github.com/Infomaniak/android-kMail/pull/2385

feat: Hide reaction messages

---

app/src/main/java/com/infomaniak/mail/data/models/message/EmojiReactionNotAllowedReason.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/emojiPicker/EmojiPickerBottomSheetDialog.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

Add the different strings translated by iOS to the emoji reactions errors and define them inside `InfomaniakCore.apiErrorCodes`
Depends on #2395

feat: Translate emoji reaction errors

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/models/MessageUi.kt
app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt

Fake emojis locally when they are clicked so the UX is quick and responsive. In the meanwhile the code will try to send the emoji for real and only undo the faked reaction if the api call has failed.
This required to introduce a MessageUi model because relying on the database model made it impossible to fake reactions at the UI level. MessageUi mainly wraps the existing Message instance so I don't have to refactor the whole app.
For now reactions are only faked locally but some buttons can be clicked even though they should not. This is handled in later PRs.
Depends on #2432

feat: Fake sent emojis locally

---

app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/utils/EmojiReactionUtils.kt
app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt

We locally detect that the user has already sent an emoji, that he has already reacted 5 times or that he has no internet connection to reply with an emoji to block his action. This lets us avoid making useless api calls.
Depends on #2433

feat: Prevent sending emojis when not allowed

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/AddReactionChip.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/models/MessageUi.kt
app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt

The emoji reactions chips should only be displayed when the feature is available and when the message can be reacted to. This PR hides it otherwise.
Depends on #2434

feat: Hide reactions if not available

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/data/Reaction.kt
EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
app/src/main/java/com/infomaniak/mail/data/models/message/EmojiReactionAuthor.kt
app/src/main/java/com/infomaniak/mail/data/models/message/EmojiReactionState.kt
app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadEmojiReactionsComputation.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/models/EmojiReactionAuthor.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/models/EmojiReactionAuthorUi.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/models/EmojiReactionStateUi.kt
app/src/main/java/com/infomaniak/mail/utils/EmojiReactionUtils.kt
app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
app/src/test/java/com/infomaniak/mail/EmojiReactionStateEqualityTest.kt

Update the data we store in realm to include from what author and message uid each emoji reaction comes from. This data is needed to display details of who used what emoji in a bottom sheet later on and also to be able to delete all messages that were emoji reactions alongside the target message deletion.
I also changed the data we store in realm and use in the compose code from unordered dictionaries/sets to ordered lists so the emojis are always ordered the way they were sent in the thread.
The method containsTheSameEmojiValuesAs() now checks for nullability for no reason even though we don't need it anymore because we're not using RealmDictionary anymore. The problem is fixed in the next PR because it make a lot of noise to fix it here. The tests associated with this method are also …

feat: Update emoji reaction model

---

app/build.gradle
gradle/libs.versions.toml

This will fix important issues caused by lack of update to the Android SDK 35 supporting version.
FYI, the version in Core is the version 2.10.2
Depends on https://github.com/Infomaniak/android-core/pull/455

fix: Update WorkManager with version from Core

---

app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Displays a "You have already reacted with this reaction" snackbar when clicking on an already used emoji

feat: Show a snackbar when clicking on an already used emoji

---

app/build.gradle
settings.gradle

Use the updated and fixed core for displaying the user avatars in the cross app login. With this core bump, we can now remove the module UserAvatar from the app as it has been deleted entirely.
Depends on https://github.com/Infomaniak/android-core/pull/461

fix: Correctly load user avatars in cross app login

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt

Scheduled threads in the search never had their `numberOfScheduledDrafts` computed and therefore were never treated as scheduled threads. Also, the condition to display a thread as scheduled in the thread list was limited to `FolderRole.SCHEDULED_DRAFTS` which also prevented from displaying them correctly in the search.
Now we use the same logic as iOS in this regard

fix: Fix scheduled thread display in search

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
EmojiComponents/src/main/res/values/attrs.xml
app/src/main/java/com/infomaniak/mail/ui/components/MailBottomSheetScaffold.kt
app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt
app/src/main/res/layout/item_message.xml

ViewCompositionStrategy were missing from the AbstractComposeView used for the emoji reaction feature. This PR adds them.
To not forget to adapt the ViewCompositionStrategy of EmojiReactionsView correctly when used in other situations, I made it necessary to be provided whenever EmojiReactionsView is defined inside of XML

feat: Add missing view composition strategy in emoji reaction feature

---

EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactionDetails.kt
app/src/main/java/com/infomaniak/mail/ui/main/thread/EmojiReactionDetailsBottomSheet.kt

SnapshotStateList already knows and notifies the code of state changes, no need to pass it as a lambda

refactor: Remove useless lambda around compose state

---

.github/workflows/android.yml
.github/workflows/ui-tests.yml

Matrices were used at some point in kDrive for ReactiveCircus/android-emulator-runner but the code is long gone and the matrices are not read anymore yet they are still in the code for no reason.

chore: Clean useless matrices

---

app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt

The system seems to animate these custom views in some rare occasions which causes the TransitionManager to try and call addView() on the root View of the custom view. When using AbstractComposeView as the root view, calls to addView() crash because it's unsupported. To fix the issue, the root view was changed to a view that supports addView().
Fixes MAIL-ANDROID-P6M

fix: Wrap MailBottomSheetScaffoldComposeView into a FrameLayout to avoid animation crash

---

app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt

Use new body preview formater created for #2586 in ThreadList.
Depends on #2586 
|  Before  |  After | 
|---|---|
|  <img width="1080" height="2400" alt="Screenshot_20250923_100222" src="https://github.com/user-attachments/assets/1c8760e7-0c18-49e4-95e1-d08d3fde103b" />  | <img width="1080" height="2400" alt="Screenshot_20250923_100058" src="https://github.com/user-attachments/assets/bd79c9cf-acbb-45d7-8480-8db49dda2854" />|

feat: Use new body preview formater in ThreadList

---

app/src/main/java/com/infomaniak/mail/views/itemViews/SelectableItemView.kt
app/src/main/res/color/button_toggle_text.xml
app/src/main/res/color/chip_contact_text_color.xml
app/src/main/res/layout/new_account_storage_chips.xml
app/src/main/res/layout/view_main_actions.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Fixes all places in the code where we forgot to use `onPrimaryContainer` when drawing content on top of a `primaryContainer` surface.
Also adapts the material dynamic default palette by overriding the values for `primaryContainer` and `onPrimaryContainer` so they look and feel like the pink and blue themes.
This fixes the issue where the palette exposed through material expressive now has a much more vivid color for the primaryContainer color leading to other unusable contrasts, where as our pink and blue designs are designed with a faded color in mind.
I also removed the unused colors `pinkOnboardingSecondaryBackground` and `blueOnboardingSecondaryBackground` that I found by chance

fix: Fix material dynamic colors

---

HtmlCleaner/build.gradle.kts

Depends on https://github.com/Infomaniak/android-core/pull/527

refactor: Remove now useless `targetSdk` in libraries

---

app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/ThreadRecomputations.kt

The back did not send the `emoji_reaction` field in messages when querying them from the search which prevented hiding the emoji reactions from threads when searching for a specific folder.
This PR adds the new query param they just added to also get the required data when querying the search.
We never had any emojis so some code inside of recomputeMessagesWithContent() was never called for the search but now that it's possible the code needed to be adapted slightly as well

fix: Add query param to receive emoji_reaction field from the search

---

app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt

This check needs to be updated to take into account the new visual structure added with FolderUi when selecting who to expand automatically. 
This was the opportunity to take this code out of the FolderController which was too much logic heavy to be inside of FolderController.upsertFolders().
At the same time I added the fix for the case where all children of a parent have been removed and at least a new child has been added to the parent. Previously the new children would remain visible even though the parent would be collapsed. Now their state is update to match the one of the parent.
Depends on #2637

feat: Update the automatic expand on empty folders code because of FolderUi and improve it
